kelseyde/calvin-chess-engine

src/main/java/com/kelseyde/calvin/board/Board.java
src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Score of Calvin DEV vs Calvin: 3297 - 3137 - 1774  [0.510] 8208
Terminating process of engine Calvin(5)
Finished game 8218 (Calvin vs Calvin DEV): * {No result}
Score of Calvin DEV vs Calvin: 3297 - 3137 - 1774  [0.510] 8208
...      Calvin DEV playing White: 1722 - 1513 - 870  [0.525] 4105
...      Calvin DEV playing Black: 1575 - 1624 - 904  [0.494] 4103
...      White vs Black: 3346 - 3088 - 1774  [0.516] 8208
Elo difference: 6.8 +/- 6.6, LOS: 97.7 %, DrawRatio: 21.6 %
```

Extend search 1 ply when entering a pawn endgame

---

src/main/java/com/kelseyde/calvin/evaluation/Evaluator.java

```
Finished game 1019 (Calvin DEV vs Calvin): * {No result}
Score of Calvin DEV vs Calvin: 363 - 339 - 307  [0.512] 1009
...      Calvin DEV playing White: 191 - 177 - 137  [0.514] 505
...      Calvin DEV playing Black: 172 - 162 - 170  [0.510] 504
...      White vs Black: 353 - 349 - 307  [0.502] 1009
Elo difference: 8.3 +/- 17.9, LOS: 81.7 %, DrawRatio: 30.4 %
```

Optimize material calculation

---

src/main/resources/engine_config.json

```
Score of Calvin DEV vs Calvin: 101 - 84 - 337  [0.516] 522
...      Calvin DEV playing White: 77 - 14 - 170  [0.621] 261
...      Calvin DEV playing Black: 24 - 70 - 167  [0.412] 261
...      White vs Black: 147 - 38 - 337  [0.604] 522
Elo difference: 11.3 +/- 17.7, LOS: 89.4 %, DrawRatio: 64.6 %
```

Allow RDP at depth 5

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Score of Calvin DEV vs Calvin: 289 - 225 - 849  [0.523] 1363
...      Calvin DEV playing White: 221 - 63 - 398  [0.616] 682
...      Calvin DEV playing Black: 68 - 162 - 451  [0.431] 681
...      White vs Black: 383 - 131 - 849  [0.592] 1363
Elo difference: 16.3 +/- 11.3, LOS: 99.8 %, DrawRatio: 62.3 %
```

Increase nmp reduction to 1 + (2 + depth / 3)

---

src/main/java/com/kelseyde/calvin/search/moveordering/MoveOrderer.java

```
Score of Calvin DEV vs Calvin: 395 - 343 - 1422  [0.512] 2160
...      Calvin DEV playing White: 302 - 79 - 699  [0.603] 1080
...      Calvin DEV playing Black: 93 - 264 - 723  [0.421] 1080
...      White vs Black: 566 - 172 - 1422  [0.591] 2160
Elo difference: 8.4 +/- 8.6, LOS: 97.2 %, DrawRatio: 65.8 %
```

History gravity

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Score of Calvin DEV vs Calvin: 180 - 133 - 550  [0.527] 863
...      Calvin DEV playing White: 143 - 34 - 254  [0.626] 431
...      Calvin DEV playing Black: 37 - 99 - 296  [0.428] 432
...      White vs Black: 242 - 71 - 550  [0.599] 863
Elo difference: 18.9 +/- 13.9, LOS: 99.6 %, DrawRatio: 63.7 %
```

Allow full LMR depth reduction in check

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

I am a big dumb idiot
The variable movesSearched is initialised to 0 and then immediately incremented after makeMove. Therefore the first move in every node is always searched with a null window...
Very embarrassing, on the other hand easiest 30 elo ever:
```
Score of Calvin DEV vs Calvin: 182 - 112 - 438  [0.548] 732
...      Calvin DEV playing White: 134 - 26 - 207  [0.647] 367
...      Calvin DEV playing Black: 48 - 86 - 231  [0.448] 365
...      White vs Black: 220 - 74 - 438  [0.600] 732
Elo difference: 33.3 +/- 15.9, LOS: 100.0 %, DrawRatio: 59.8 %
```

Stop searching first PV node with null window

---

src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/java/com/kelseyde/calvin/search/picker/MovePicker.java
src/test/java/com/kelseyde/calvin/search/picker/MovePickerTest.java

Stopping early as this is just a non-functional speedup
```
Score of Calvin DEV vs Calvin: 172 - 147 - 431  [0.517] 750
...      Calvin DEV playing White: 120 - 39 - 215  [0.608] 374
...      Calvin DEV playing Black: 52 - 108 - 216  [0.426] 376
...      White vs Black: 228 - 91 - 431  [0.591] 750
Elo difference: 11.6 +/- 16.2, LOS: 91.9 %, DrawRatio: 57.5 %
```

Stop calling ```MoveGenerator``` twice when in check

---

TODO.md
src/main/java/com/kelseyde/calvin/engine/Engine.java
src/main/java/com/kelseyde/calvin/engine/EngineInitializer.java
src/main/java/com/kelseyde/calvin/search/ParallelSearcher.java
src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/java/com/kelseyde/calvin/utils/train/TrainingDataScorer.java
src/test/java/com/kelseyde/calvin/utils/TestUtils.java

I have absolutely no explanation for this - I thought it would be a non-functional change. Must be too small sample size.
```
Score of Calvin DEV vs Calvin: 151 - 110 - 332  [0.535] 593
...      Calvin DEV playing White: 114 - 25 - 158  [0.650] 297
...      Calvin DEV playing Black: 37 - 85 - 174  [0.419] 296
...      White vs Black: 199 - 62 - 332  [0.616] 593
Elo difference: 24.1 +/- 18.5, LOS: 99.4 %, DrawRatio: 56.0 %
```

Simplify Searcher initialisation

---

src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/resources/engine_config.json

```
Score of Calvin DEV vs Calvin: 151 - 117 - 337  [0.528] 605
...      Calvin DEV playing White: 115 - 24 - 163  [0.651] 302
...      Calvin DEV playing Black: 36 - 93 - 174  [0.406] 303
...      White vs Black: 208 - 60 - 337  [0.622] 605
Elo difference: 19.5 +/- 18.4, LOS: 98.1 %, DrawRatio: 55.7 %
```

Tweak lmr min moves + reduction

---

src/main/java/com/kelseyde/calvin/engine/EngineConfig.java
src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/resources/engine_config.json
src/test/resources/engine_config.json

Merging early because I'm impatient and it's been stable at + ~8 forever.
```
Score of Calvin DEV vs Calvin: 366 - 330 - 795  [0.512] 1491
...      Calvin DEV playing White: 271 - 87 - 388  [0.623] 746
...      Calvin DEV playing Black: 95 - 243 - 407  [0.401] 745
...      White vs Black: 514 - 182 - 795  [0.611] 1491
Elo difference: 8.4 +/- 12.0, LOS: 91.4 %, DrawRatio: 53.3 %
```

Quiescence search futility pruning

---

src/main/java/com/kelseyde/calvin/search/SearchHistory.java
src/main/java/com/kelseyde/calvin/search/Searcher.java

Fixing a regression from previous refactors
```
Score of Calvin DEV vs Calvin: 111 - 82 - 297  [0.530] 490
...      Calvin DEV playing White: 83 - 22 - 141  [0.624] 246
...      Calvin DEV playing Black: 28 - 60 - 156  [0.434] 244
...      White vs Black: 143 - 50 - 297  [0.595] 490
Elo difference: 20.6 +/- 19.3, LOS: 98.2 %, DrawRatio: 60.6 %
```

Only update killer on fail high

---

src/main/java/com/kelseyde/calvin/engine/EngineConfig.java
src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/resources/engine_config.json
src/test/resources/engine_config.json

```
Score of Calvin DEV vs Calvin: 640 - 570 - 1350  [0.514] 2560
...      Calvin DEV playing White: 454 - 163 - 663  [0.614] 1280
...      Calvin DEV playing Black: 186 - 407 - 687  [0.414] 1280
...      White vs Black: 861 - 349 - 1350  [0.600] 2560
Elo difference: 9.5 +/- 9.2, LOS: 97.8 %, DrawRatio: 52.7 %
```

Tweak futility pruning formula

---

src/main/java/com/kelseyde/calvin/board/Bits.java
src/main/java/com/kelseyde/calvin/movegen/MoveGenerator.java
src/test/java/com/kelseyde/calvin/movegen/PinCalculatorTest.java

Quick regression test
```
Score of Calvin DEV vs Calvin: 128 - 117 - 276  [0.511] 521
...      Calvin DEV playing White: 91 - 29 - 140  [0.619] 260
...      Calvin DEV playing Black: 37 - 88 - 136  [0.402] 261
...      White vs Black: 179 - 66 - 276  [0.608] 521
Elo difference: 7.3 +/- 20.5, LOS: 75.9 %, DrawRatio: 53.0 %
```

Fix pin bug

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

Quick regression test, this is only the most fractional of speedups (less makemoves):
```
Score of Calvin DEV vs Calvin: 254 - 252 - 497  [0.501] 1003
...      Calvin DEV playing White: 190 - 60 - 252  [0.629] 502
...      Calvin DEV playing Black: 64 - 192 - 245  [0.372] 501
...      White vs Black: 382 - 124 - 497  [0.629] 1003
Elo difference: 0.7 +/- 15.3, LOS: 53.5 %, DrawRatio: 49.6 %
```

Move history pruning before makemove

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

Stopping early since literally dozens of other engines don't do this.
```
Score of Calvin DEV vs Calvin: 702 - 677 - 1427  [0.504] 2806
...      Calvin DEV playing White: 533 - 153 - 717  [0.635] 1403
...      Calvin DEV playing Black: 169 - 524 - 710  [0.373] 1403
...      White vs Black: 1057 - 322 - 1427  [0.631] 2806
Elo difference: 3.1 +/- 9.0, LOS: 75.0 %, DrawRatio: 50.9 %
```

Stop writing to TT in NMP

---

src/main/java/com/kelseyde/calvin/search/SearchHistory.java
src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/java/com/kelseyde/calvin/search/picker/MovePicker.java
src/main/java/com/kelseyde/calvin/tables/history/QuietHistoryTable.java

Merging early because most other engines do it, it uses up fractionally less memory, and it brings the quiet history table in line with the other tables.
```
Score of Calvin DEV vs Calvin: 265 - 250 - 522  [0.507] 1037
...      Calvin DEV playing White: 207 - 54 - 257  [0.648] 518
...      Calvin DEV playing Black: 58 - 196 - 265  [0.367] 519
...      White vs Black: 403 - 112 - 522  [0.640] 1037
Elo difference: 5.0 +/- 14.9, LOS: 74.6 %, DrawRatio: 50.3 %
```

Use piece/to indexing for quiet history table

---

src/main/java/com/kelseyde/calvin/engine/Engine.java
src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/java/com/kelseyde/calvin/tables/tt/HashEntry.java
src/main/java/com/kelseyde/calvin/tables/tt/TranspositionTable.java
src/test/java/com/kelseyde/calvin/tables/ContHistTableTest.java
src/test/java/com/kelseyde/calvin/tables/TranspositionTableTest.java

Using two arrays of 64-bit longs instead of a full Java class with all it's padding + header shenanigans. 
```
Score of Calvin DEV vs Calvin: 627 - 531 - 1430  [0.519] 2588
...      Calvin DEV playing White: 495 - 112 - 687  [0.648] 1294
...      Calvin DEV playing Black: 132 - 419 - 743  [0.389] 1294
...      White vs Black: 914 - 244 - 1430  [0.629] 2588
Elo difference: 12.9 +/- 8.9, LOS: 99.8 %, DrawRatio: 55.3 %
```

Compress TT

---

src/main/java/com/kelseyde/calvin/engine/EngineConfig.java
src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Score of Calvin DEV vs Calvin: 1346 - 1211 - 2806  [0.513] 5363
...      Calvin DEV playing White: 1083 - 235 - 1364  [0.658] 2682
...      Calvin DEV playing Black: 263 - 976 - 1442  [0.367] 2681
...      White vs Black: 2059 - 498 - 2806  [0.646] 5363
Elo difference: 8.7 +/- 6.4, LOS: 99.6 %, DrawRatio: 52.3 %
SPRT: llr 2.91 (100.8%), lbound -2.25, ubound 2.89 - H1 was accepted
```

TT non cutoff extension

---

src/main/java/com/kelseyde/calvin/search/SearchHistory.java
src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/java/com/kelseyde/calvin/search/picker/MovePicker.java

Previously was using quiet history score for capture LMR, which doesn't make any sense. 
```
Score of Calvin DEV vs Calvin: 2165 - 2125 - 4283  [0.502] 8573
...      Calvin DEV playing White: 1717 - 410 - 2160  [0.652] 4287
...      Calvin DEV playing Black: 448 - 1715 - 2123  [0.352] 4286
...      White vs Black: 3432 - 858 - 4283  [0.650] 8573
Elo difference: 1.6 +/- 5.2, LOS: 72.9 %, DrawRatio: 50.0 %
```

Capthist late move reductions

---

src/main/java/com/kelseyde/calvin/engine/EngineConfig.java
src/main/java/com/kelseyde/calvin/search/Searcher.java

To be SPSA'd later, for now same values as for quiets.
Quick regtest:
```
Score of Calvin DEV vs Calvin: 290 - 283 - 427  [0.503] 1000
...      Calvin DEV playing White: 220 - 71 - 209  [0.649] 500
...      Calvin DEV playing Black: 70 - 212 - 218  [0.358] 500
...      White vs Black: 432 - 141 - 427  [0.645] 1000
Elo difference: 2.4 +/- 16.3, LOS: 61.5 %, DrawRatio: 42.7 %
```

Seprate LMR table for noisies

---

src/main/java/com/kelseyde/calvin/engine/EngineConfig.java
src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Score of Calvin DEV vs Calvin: 1763 - 1614 - 3435  [0.511] 6812
...      Calvin DEV playing White: 1352 - 383 - 1671  [0.642] 3406
...      Calvin DEV playing Black: 411 - 1231 - 1764  [0.380] 3406
...      White vs Black: 2583 - 794 - 3435  [0.631] 6812
Elo difference: 7.6 +/- 5.8, LOS: 99.5 %, DrawRatio: 50.4 %
SPRT: llr 2.9 (100.5%), lbound -2.25, ubound 2.89 - H1 was accepted
```

NMP eval-based reduction

---

src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/java/com/kelseyde/calvin/search/picker/MovePicker.java

Probably doesn't make much difference, but I'm merging as it's just incorrect to treat them as quiets.
```
Score of Calvin DEV vs Calvin: 355 - 353 - 502  [0.501] 1210
...      Calvin DEV playing White: 242 - 106 - 257  [0.612] 605
...      Calvin DEV playing Black: 113 - 247 - 245  [0.389] 605
...      White vs Black: 489 - 219 - 502  [0.612] 1210
Elo difference: 0.6 +/- 15.0, LOS: 53.0 %, DrawRatio: 41.5 %
```

Treat en passants as capture moves in search

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

Tighten RFP pruning margin and add a softer margin where, instead of pruning, all quiet moves are reduced.
STC:
```
Score of Calvin DEV vs Calvin: 1397 - 1244 - 1748  [0.517] 4389
...      Calvin DEV playing White: 972 - 360 - 863  [0.639] 2195
...      Calvin DEV playing Black: 425 - 884 - 885  [0.395] 2194
...      White vs Black: 1856 - 785 - 1748  [0.622] 4389
Elo difference: 12.1 +/- 8.0, LOS: 99.9 %, DrawRatio: 39.8 %
SPRT: llr 2.91 (100.6%), lbound -2.25, ubound 2.89 - H1 was accepted
```

RFP quiet reductions

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Score of Calvin DEV vs Calvin: 2022 - 1853 - 2439  [0.513] 6314
...      Calvin DEV playing White: 1364 - 575 - 1219  [0.625] 3158
...      Calvin DEV playing Black: 658 - 1278 - 1220  [0.402] 3156
...      White vs Black: 2642 - 1233 - 2439  [0.612] 6314
Elo difference: 9.3 +/- 6.7, LOS: 99.7 %, DrawRatio: 38.6 %
```

Futility reductions

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Score of Calvin DEV vs Calvin: 1227 - 1073 - 1308  [0.521] 3608
...      Calvin DEV playing White: 828 - 326 - 651  [0.639] 1805
...      Calvin DEV playing Black: 399 - 747 - 657  [0.403] 1803
...      White vs Black: 1575 - 725 - 1308  [0.618] 3608
Elo difference: 14.8 +/- 9.0, LOS: 99.9 %, DrawRatio: 36.3 %
SPRT: llr 2.89 (100.1%), lbound -2.25, ubound 2.89 - H1 was accepted
```

Variable-depth reverse futility reductions

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Score of Calvin DEV vs Calvin: 3911 - 3699 - 5086  [0.508] 12696
...      Calvin DEV playing White: 2755 - 1123 - 2471  [0.629] 6349
...      Calvin DEV playing Black: 1156 - 2576 - 2615  [0.388] 6347
...      White vs Black: 5331 - 2279 - 5086  [0.620] 12696
Elo difference: 5.8 +/- 4.7, LOS: 99.2 %, DrawRatio: 40.1 %
SPRT: llr 2.9 (100.2%), lbound -2.25, ubound 2.89 - H1 was accepted
```

Variable-depth futility reductions

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

Merging early because it is obviously incorrect. 
```
Score of Calvin DEV vs Calvin: 1311 - 1233 - 1819  [0.509] 4363
...      Calvin DEV playing White: 933 - 337 - 912  [0.637] 2182
...      Calvin DEV playing Black: 378 - 896 - 907  [0.381] 2181
...      White vs Black: 1829 - 715 - 1819  [0.628] 4363
Elo difference: 6.2 +/- 7.9, LOS: 93.9 %, DrawRatio: 41.7 %
```

Dont check depth for TT cutoffs in qsearch

---

src/main/java/com/kelseyde/calvin/board/Board.java
src/main/java/com/kelseyde/calvin/engine/Engine.java

As pointed out by Stormphrax author after some crashes in CCRL tests.
Merging early, since this was clearly incorrect behaviour and the benefits will probably only be noticed at LTC. 
```
Score of Calvin DEV vs Calvin: 987 - 918 - 2208  [0.508] 4113
...      Calvin DEV playing White: 698 - 261 - 1098  [0.606] 2057
...      Calvin DEV playing Black: 289 - 657 - 1110  [0.411] 2056
...      White vs Black: 1355 - 550 - 2208  [0.598] 4113
Elo difference: 5.8 +/- 7.2, LOS: 94.3 %, DrawRatio: 53.7 %
```

Reset ply counter to 0 after applying moves from UCI

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Score of Calvin DEV vs Calvin: 2340 - 2168 - 3403  [0.511] 7911
...      Calvin DEV playing White: 1661 - 589 - 1707  [0.635] 3957
...      Calvin DEV playing Black: 679 - 1579 - 1696  [0.386] 3954
...      White vs Black: 3240 - 1268 - 3403  [0.625] 7911
Elo difference: 7.6 +/- 5.8, LOS: 99.5 %, DrawRatio: 43.0 %
SPRT: llr 2.91 (100.6%), lbound -2.25, ubound 2.89 - H1 was accepted
```

Apply futility reduction also to bad noisies

---

src/main/java/com/kelseyde/calvin/uci/UCI.java

Non-functional, quick regresstion test:
```
Score of Calvin DEV vs Calvin: 114 - 119 - 404  [0.496] 637
...      Calvin DEV playing White: 97 - 29 - 193  [0.607] 319
...      Calvin DEV playing Black: 17 - 90 - 211  [0.385] 318
...      White vs Black: 187 - 46 - 404  [0.611] 637
Elo difference: -2.7 +/- 16.3, LOS: 37.2 %, DrawRatio: 63.4 %
```

Disable pretty print for tournament runners

---

src/main/java/com/kelseyde/calvin/tables/tt/TranspositionTable.java
src/main/resources/TODO.md

```
Score of Calvin DEV vs Calvin: 544 - 431 - 1012  [0.528] 1987
...      Calvin DEV playing White: 448 - 72 - 474  [0.689] 994
...      Calvin DEV playing Black: 96 - 359 - 538  [0.368] 993
...      White vs Black: 807 - 168 - 1012  [0.661] 1987
Elo difference: 19.8 +/- 10.7, LOS: 100.0 %, DrawRatio: 50.9 %
SPRT: llr 2.91 (100.6%), lbound -2.25, ubound 2.89 - H1 was accepted
```

Overwrite TT entries where depth >= ttDepth - 4

---

src/main/java/com/kelseyde/calvin/board/Bits.java
src/main/java/com/kelseyde/calvin/board/Board.java
src/main/java/com/kelseyde/calvin/movegen/MoveGenerator.java
src/main/java/com/kelseyde/calvin/search/SEE.java
src/main/java/com/kelseyde/calvin/search/Searcher.java
src/test/java/com/kelseyde/calvin/evaluation/SEETest.java
src/test/resources/see_suite.epd

Yoinked from every other engine under the sun - Calvin finally uses a proper SEE algorithm and not the make/unmake implementation I've used since the very beginning.
Hopefully SEE pruning finally gains now...
```
Score of Calvin DEV vs Calvin: 1548 - 1399 - 2461  [0.514] 5408
...      Calvin DEV playing White: 1181 - 332 - 1191  [0.657] 2704
...      Calvin DEV playing Black: 367 - 1067 - 1270  [0.371] 2704
...      White vs Black: 2248 - 699 - 2461  [0.643] 5408
Elo difference: 9.6 +/- 6.8, LOS: 99.7 %, DrawRatio: 45.5 %
SPRT: llr 2.91 (100.7%), lbound -2.25, ubound 2.89 - H1 was accepted
```

Use improved SEE algorithm

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Score of Calvin DEV vs Calvin: 1251 - 1108 - 1841  [0.517] 4200
...      Calvin DEV playing White: 950 - 264 - 886  [0.663] 2100
...      Calvin DEV playing Black: 301 - 844 - 955  [0.371] 2100
...      White vs Black: 1794 - 565 - 1841  [0.646] 4200
Elo difference: 11.8 +/- 7.9, LOS: 99.8 %, DrawRatio: 43.8 %
SPRT: llr 2.89 (100.1%), lbound -2.25, ubound 2.89 - H1 was accepted
```

PVS SEE noisy pruning

---

src/main/java/com/kelseyde/calvin/search/picker/MovePicker.java

Let's go!
```
Score of Calvin DEV vs Calvin: 575 - 448 - 772  [0.535] 1795
...      Calvin DEV playing White: 408 - 116 - 374  [0.663] 898
...      Calvin DEV playing Black: 167 - 332 - 398  [0.408] 897
...      White vs Black: 740 - 283 - 772  [0.627] 1795
Elo difference: 24.6 +/- 12.1, LOS: 100.0 %, DrawRatio: 43.0 %
SPRT: llr 2.89 (100.1%), lbound -2.25, ubound 2.89 - H1 was accepted
```

Use SEE to separate good and bad noisies

---

src/main/java/com/kelseyde/calvin/search/picker/MovePicker.java

```
Score of Calvin DEV vs Calvin: 4058 - 3844 - 6604  [0.507] 14506
...      Calvin DEV playing White: 3132 - 847 - 3274  [0.658] 7253
...      Calvin DEV playing Black: 926 - 2997 - 3330  [0.357] 7253
...      White vs Black: 6129 - 1773 - 6604  [0.650] 14506
Elo difference: 5.1 +/- 4.2, LOS: 99.2 %, DrawRatio: 45.5 %
SPRT: llr 2.9 (100.2%), lbound -2.25, ubound 2.89 - H1 was accepted
```

Use negative pawn threshold for SEE move ordering

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

Merging early as this should only be a minor speedup.
```
Score of Calvin DEV vs Calvin: 1454 - 1404 - 2142  [0.505] 5000
...      Calvin DEV playing White: 1120 - 336 - 1045  [0.657] 2501
...      Calvin DEV playing Black: 334 - 1068 - 1097  [0.353] 2499
...      White vs Black: 2188 - 670 - 2142  [0.652] 5000
Elo difference: 3.5 +/- 7.3, LOS: 82.5 %, DrawRatio: 42.8 %
```

Put PVS SEE pruning last in move-loop-pruning

---

src/main/java/com/kelseyde/calvin/engine/EngineConfig.java
src/main/java/com/kelseyde/calvin/search/TimeControl.java

Non-reg:
```
Score of Calvin DEV vs Calvin: 612 - 604 - 784  [0.502] 2000
...      Calvin DEV playing White: 432 - 173 - 396  [0.629] 1001
...      Calvin DEV playing Black: 180 - 431 - 388  [0.374] 999
...      White vs Black: 863 - 353 - 784  [0.627] 2000
Elo difference: 1.4 +/- 11.9, LOS: 59.1 %, DrawRatio: 39.2 %
```

Make time and increment factors tunable

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Score of Calvin DEV vs Calvin: 1749 - 1587 - 2160  [0.515] 5496
...      Calvin DEV playing White: 1233 - 451 - 1065  [0.642] 2749
...      Calvin DEV playing Black: 516 - 1136 - 1095  [0.387] 2747
...      White vs Black: 2369 - 967 - 2160  [0.628] 5496
Elo difference: 10.2 +/- 7.1, LOS: 99.7 %, DrawRatio: 39.3 %
SPRT: llr 2.91 (100.5%), lbound -2.25, ubound 2.89 - H1 was accepted
```

Stop doing QS SEE pruning when in check

---

src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/java/com/kelseyde/calvin/search/picker/MovePicker.java

```
Score of Calvin DEV vs Calvin: 2015 - 1851 - 2867  [0.512] 6733
...      Calvin DEV playing White: 1499 - 457 - 1412  [0.655] 3368
...      Calvin DEV playing Black: 516 - 1394 - 1455  [0.370] 3365
...      White vs Black: 2893 - 973 - 2867  [0.643] 6733
Elo difference: 8.5 +/- 6.3, LOS: 99.6 %, DrawRatio: 42.6 %
SPRT: llr 2.9 (100.2%), lbound -2.25, ubound 2.89 - H1 was accepted
```

Stop excluding killers/promotions from history bonuses

---

src/main/java/com/kelseyde/calvin/search/picker/MovePicker.java

```
Score of Calvin DEV vs Calvin: 2878 - 2694 - 4526  [0.509] 10098
...      Calvin DEV playing White: 2203 - 629 - 2219  [0.656] 5051
...      Calvin DEV playing Black: 675 - 2065 - 2307  [0.362] 5047
...      White vs Black: 4268 - 1304 - 4526  [0.647] 10098
Elo difference: 6.3 +/- 5.0, LOS: 99.3 %, DrawRatio: 44.8 %
SPRT: llr 2.9 (100.5%), lbound -2.25, ubound 2.89 - H1 was accepted
```

Stop q-searching bad noisies

---

src/main/java/com/kelseyde/calvin/search/picker/MovePicker.java

Non-functional as captured is never null in Q-search.
```
Score of Calvin DEV vs Calvin: 2721 - 2732 - 4606  [0.499] 10059
...      Calvin DEV playing White: 2066 - 628 - 2335  [0.643] 5029
...      Calvin DEV playing Black: 655 - 2104 - 2271  [0.356] 5030
...      White vs Black: 4170 - 1283 - 4606  [0.644] 10059
Elo difference: -0.4 +/- 5.0, LOS: 44.1 %, DrawRatio: 45.8 %
```

Simplify Q-search MovePicker logic

---

src/main/java/com/kelseyde/calvin/search/SearchHistory.java
src/main/java/com/kelseyde/calvin/tables/history/QuietHistoryTable.java

Merging early as I should have run a non-reg - history ageing is pointless combined with the gravity formula
```
Score of Calvin DEV vs Calvin: 4179 - 4079 - 6742  [0.503] 15000
...      Calvin DEV playing White: 3153 - 960 - 3388  [0.646] 7501
...      Calvin DEV playing Black: 1026 - 3119 - 3354  [0.360] 7499
...      White vs Black: 6272 - 1986 - 6742  [0.643] 15000
Elo difference: 2.3 +/- 4.1, LOS: 86.4 %, DrawRatio: 44.9 %
```

Remove history ageing

---

src/main/java/com/kelseyde/calvin/engine/EngineConfig.java
src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Elo   | 2.26 +- 2.00 (95%)
LLR   | 2.30 (-2.89, 2.25) [0.00, 5.00]
Games | N: 37162 W: 8773 L: 8531 D: 19858
Penta | [352, 4411, 8838, 4603, 377]
```
https://kelseyde.pythonanywhere.com/test/23/
bench 6738478

Aspiration window tweaks

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

Not a great idea when staticEval = Integer.MIN_VALUE...
```
Elo   | 6.36 +- 4.88 (95%)
LLR   | 2.25 (-2.89, 2.25) [0.00, 5.00]
Games | N: 6230 W: 1508 L: 1394 D: 3328
Penta | [60, 688, 1517, 778, 72]
```
https://kelseyde.pythonanywhere.com/test/25/
bench 5977743

Stop doing futility pruning in check

---

src/main/java/com/kelseyde/calvin/engine/EngineConfig.java

```
Elo   | 5.38 +- 4.32 (95%)
Games | N: 7616 W: 1806 L: 1688 D: 4122
Penta | [51, 890, 1823, 978, 66]
```
https://kelseyde.pythonanywhere.com/test/44/
bench 4344458

Increase LMP depth

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

STC:
```
Elo   | 2.55 +- 2.34 (95%)
Games | N: 26606 W: 6382 L: 6187 D: 14037
Penta | [220, 3145, 6430, 3236, 272]
```
https://kelseyde.pythonanywhere.com/test/58/
bench 4282776

History bonus if bestScore > beta + 50

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

STC:
```
Elo   | 7.19 +- 5.22 (95%)
LLR   | 2.29 (-2.89, 2.25) [0.00, 5.00]
Games | N: 5364 W: 1295 L: 1184 D: 2885
Penta | [45, 600, 1292, 689, 56]
```
https://kelseyde.pythonanywhere.com/test/54/
bench 4687225

Do check extension inside move loop

---

src/main/java/com/kelseyde/calvin/engine/EngineConfig.java
src/main/java/com/kelseyde/calvin/search/Searcher.java

And use 0 as a flat threshold for Q-search SEE pruning
STC: 
```
Elo   | 3.93 +- 3.47 (95%)
LLR   | 2.27 (-2.89, 2.25) [0.00, 5.00]
Games | N: 12104 W: 2874 L: 2737 D: 6493
Penta | [108, 1383, 2950, 1486, 125]
```
https://kelseyde.pythonanywhere.com/test/71/

Remove 'depth' parameter from Q-search

---

src/main/java/com/kelseyde/calvin/movegen/MoveGenerator.java
src/test/java/com/kelseyde/calvin/movegen/Chess960Test.java
src/test/java/com/kelseyde/calvin/movegen/PseudoLegalTest.java

Hello,
Here are the minor bugs fixed by this pull request:
- MoveGenerator.isPseudoLegal returned false on some queen side standard castling.
- MoveGenerator.isPseudoLegal did not work with chess960.
- MoveGenerator.getMoves did not return castling move when king did not
move and rook traverses it (see test
Chess960Test.testKingDoesntMoveCastling).
I also want to thank you warmly for sharing this code, as efficient as it is clear.  
I would like to reuse it, if you agree, I will open an issue/proposal about how to do that.
Best regards
Jean-Marc

Bug fixes for MoveGenerator isPseudoLegal and getMoves (most in chess960)

---

src/main/java/com/kelseyde/calvin/engine/EngineConfig.java
src/main/java/com/kelseyde/calvin/search/Searcher.java

STC:
```
Elo   | 3.05 +- 2.80 (95%)
LLR   | 2.25 (-2.89, 2.25) [0.00, 5.00]
Games | N: 18254 W: 4325 L: 4165 D: 9764
Penta | [159, 2099, 4456, 2249, 164]
```
https://kelseyde.pythonanywhere.com/test/79/
bench 4284363

Use history score in PVS SEE pruning

---

src/main/java/com/kelseyde/calvin/engine/EngineConfig.java
src/main/java/com/kelseyde/calvin/search/Searcher.java

STC:
```
Elo   | 3.11 +- 2.84 (95%)
LLR   | 2.27 (-2.89, 2.25) [0.00, 5.00]
Games | N: 17770 W: 4254 L: 4095 D: 9421
Penta | [132, 2104, 4293, 2185, 171]
```
https://kelseyde.pythonanywhere.com/test/88/
bench 5707708

Tune depth margins

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

STC:
```
Elo   | 3.30 +- 2.97 (95%)
LLR   | 2.32 (-2.89, 2.25) [0.00, 5.00]
Games | N: 16448 W: 3873 L: 3717 D: 8858
Penta | [139, 1926, 3943, 2072, 144]
```
https://kelseyde.pythonanywhere.com/test/99/
bench 5103163

Use just static eval in corrhist updates

---

src/main/java/com/kelseyde/calvin/tables/correction/HashCorrectionTable.java
src/main/java/com/kelseyde/calvin/tables/correction/PieceToCorrectionTable.java
src/main/java/com/kelseyde/calvin/tables/history/AbstractHistoryTable.java
src/main/java/com/kelseyde/calvin/tables/history/CaptureHistoryTable.java
src/main/java/com/kelseyde/calvin/tables/history/ContinuationHistoryTable.java
src/main/java/com/kelseyde/calvin/tables/history/QuietHistoryTable.java

Non-functional.
STC:
```
Elo   | -0.25 +- 3.39 (95%)
LLR   | 0.94 (-2.89, 2.25) [-5.00, 0.00]
Games | N: 11210 W: 2567 L: 2575 D: 6068
Penta | [82, 1229, 2996, 1211, 87]
```
https://kelseyde.pythonanywhere.com/test/126/
bench 5075540

Switch history tables to use i16s

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

Not sure how I could have messed this up so badly...
STC:
```
Elo   | 4.77 +- 4.00 (95%)
Games | N: 8960 W: 2101 L: 1978 D: 4881
Penta | [69, 1028, 2179, 1119, 85]
```
https://kelseyde.pythonanywhere.com/test/134/
bench 5779060

Fix futility reductions

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

Should have run this as a non-reg - it could be it loses a fractional amount of elo, but it's a simplification I quite like, so I'm merging it.
```
Elo   | -0.96 +- 3.63 (95%)
LLR   | -1.90 (-2.89, 2.25) [0.00, 5.00]
Games | N: 10890 W: 2431 L: 2461 D: 5998
Penta | [89, 1341, 2620, 1301, 94]
```
https://kelseyde.pythonanywhere.com/test/137/
bench 5209072

Remove RFP futility reductions

---

src/main/java/com/kelseyde/calvin/engine/EngineConfig.java
src/main/java/com/kelseyde/calvin/search/Searcher.java

STC:
```
Elo   | 5.28 +- 4.28 (95%)
Games | N: 7694 W: 1804 L: 1687 D: 4203
Penta | [53, 878, 1886, 959, 71]
```
https://kelseyde.pythonanywhere.com/test/149/
bench 5173416

Improve history LMR

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

Let's go
```
Elo   | 11.30 +- 6.74 (95%)
LLR   | 2.29 (-2.89, 2.25) [0.00, 5.00]
Games | N: 3046 W: 748 L: 649 D: 1649
Penta | [19, 321, 753, 402, 28]
```
https://kelseyde.pythonanywhere.com/test/154/
bench 4361925

Only skip SEE pruning for good noisies

---

src/main/java/com/kelseyde/calvin/search/picker/MoveScorer.java

STC:
```
Elo   | 2.83 +- 2.61 (95%)
Games | N: 20120 W: 4558 L: 4394 D: 11168
Penta | [141, 2308, 5019, 2430, 162]
```
https://kelseyde.pythonanywhere.com/test/171/
bench 4260855

Smaller capthist divisor

---

src/main/java/com/kelseyde/calvin/engine/EngineConfig.java
src/main/java/com/kelseyde/calvin/search/Searcher.java

STC:
```
Elo   | 4.49 +- 3.79 (95%)
Games | N: 9354 W: 2133 L: 2012 D: 5209
Penta | [67, 1033, 2353, 1160, 64]
```
https://kelseyde.pythonanywhere.com/test/232/
bench 4541662

Futility LMR

---

src/main/java/com/kelseyde/calvin/engine/EngineConfig.java
src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Elo   | 5.67 +- 4.49 (95%)
Games | N: 7042 W: 1656 L: 1541 D: 3845
Penta | [52, 799, 1719, 884, 67]
```
https://kelseyde.pythonanywhere.com/test/250/
bench 4496046

Double extensions

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Elo   | 7.04 +- 6.29 (95%)
LLR   | 2.26 (-2.89, 2.25) [-5.00, 0.00]
Games | N: 3604 W: 879 L: 806 D: 1919
Penta | [27, 412, 849, 489, 25]
```
https://kelseyde.pythonanywhere.com/test/261/
bench 4701210

Don't call evaluate() in singular search

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Elo   | 9.44 +- 6.17 (95%)
Games | N: 3790 W: 926 L: 823 D: 2041
Penta | [33, 402, 927, 495, 38]
```
https://kelseyde.pythonanywhere.com/test/289/
bench 5388612

Fix `cutnode` usage

---

src/main/java/com/kelseyde/calvin/engine/EngineConfig.java

```
Elo   | 5.78 +- 4.54 (95%)
LLR   | 2.25 (-2.89, 2.25) [0.00, 5.00]
Games | N: 6734 W: 1604 L: 1492 D: 3638
Penta | [36, 777, 1660, 827, 67]
```
https://kelseyde.pythonanywhere.com/test/291/
bench 5369229

Cutnode LMR

---

src/main/java/com/kelseyde/calvin/engine/EngineConfig.java
src/main/java/com/kelseyde/calvin/search/Searcher.java

STC:
```
Elo   | 7.40 +- 5.30 (95%)
Games | N: 4980 W: 1192 L: 1086 D: 2702
Penta | [37, 539, 1244, 621, 49]
```
https://kelseyde.pythonanywhere.com/test/318/
bench 4699795

Tweak RFP margin

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Elo   | 2.57 +- 2.35 (95%)
LLR   | 2.29 (-2.89, 2.25) [0.00, 5.00]
Games | N: 24340 W: 5617 L: 5437 D: 13286
Penta | [147, 2833, 6047, 2979, 164]
```
https://kelseyde.pythonanywhere.com/test/316/
bench 5285557

No LMR for good noisies

---

src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/java/com/kelseyde/calvin/tables/correction/CorrectionHistoryTable.java

```
Elo   | 3.08 +- 2.79 (95%)
LLR   | 2.30 (-2.20, 2.20) [0.00, 5.00]
Games | N: 17510 W: 4106 L: 3951 D: 9453
Penta | [115, 2035, 4305, 2180, 120]
```
https://kelseyde.pythonanywhere.com/test/339/
bench 4716872

Decrease corrhist scale again

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Elo   | 5.32 +- 4.33 (95%)
Games | N: 7450 W: 1788 L: 1674 D: 3988
Penta | [50, 850, 1825, 936, 64]
```
https://kelseyde.pythonanywhere.com/test/348/
bench 4581732

Allow history pruning in PV nodes

---

src/main/java/com/kelseyde/calvin/evaluation/NNUE.java

Observed some crashes when hitting `Search.MAX_DEPTH` since updating NNUE during makeMove overflows the accumulator stack, which is also initialised to size = `Search.MAX_DEPTH`...
bench 4703635

Fix crashes when updating NNUE at max depth

---

src/main/java/com/kelseyde/calvin/evaluation/activation/Screlu.java

seems to be a small speedup, local tests suggest 1-5% on zen5
```
Elo   | 1.06 +- 3.40 (95%)
SPRT  | 4.0+0.04s Threads=1 Hash=8MB
LLR   | 2.27 (-2.20, 2.20) [-5.00, 0.00]
Games | N: 12422 W: 3096 L: 3058 D: 6268
Penta | [118, 1411, 3134, 1411, 137]
```
https://kelseyde.pythonanywhere.com/test/399/
bench 4791019

Unroll inference

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

In case full-node reductions took depth to <= 0, drop into q-search.
```
Elo   | 6.93 +- 5.03 (95%)
Games | N: 4966 W: 1229 L: 1130 D: 2607
Penta | [26, 514, 1309, 603, 31]
```
https://kelseyde.pythonanywhere.com/test/419/
bench 4704922

Second q-search drop after IIR + TT reductions

---

src/main/java/com/kelseyde/calvin/search/SearchHistory.java
src/main/java/com/kelseyde/calvin/search/SearchStack.java
src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/java/com/kelseyde/calvin/search/picker/MoveScorer.java
src/main/java/com/kelseyde/calvin/tables/history/QuietHistoryTable.java
src/test/java/com/kelseyde/calvin/tables/ContHistTableTest.java

```
Elo   | 6.29 +- 4.81 (95%)
LLR   | 2.23 (-2.20, 2.20) [0.00, 5.00]
Games | N: 5912 W: 1457 L: 1350 D: 3105
Penta | [32, 673, 1455, 748, 48]
```
https://kelseyde.pythonanywhere.com/test/429/
bench 5200344

Prior countermove bonus

---

src/main/java/com/kelseyde/calvin/search/ParallelSearcher.java
src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/java/com/kelseyde/calvin/tables/tt/HashEntry.java
src/main/java/com/kelseyde/calvin/tables/tt/TranspositionTable.java
src/test/java/com/kelseyde/calvin/tables/TranspositionTableTest.java

```
Elo   | 5.38 +- 4.34 (95%)
Games | N: 7236 W: 1764 L: 1652 D: 3820
Penta | [47, 810, 1801, 904, 56]
```
https://kelseyde.pythonanywhere.com/test/450/
bench 5279706

Compress TT entry to 12 bytes

---

src/main/java/com/kelseyde/calvin/engine/EngineConfig.java
src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Elo   | 2.81 +- 2.61 (95%)
LLR   | 2.23 (-2.20, 2.20) [0.00, 5.00]
Games | N: 20736 W: 5062 L: 4894 D: 10780
Penta | [155, 2435, 5045, 2553, 180]
```
https://kelseyde.pythonanywhere.com/test/457/
bench 5756474

Scale futility margin based on move count

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Elo   | 5.11 +- 4.21 (95%)
Games | N: 7820 W: 1973 L: 1858 D: 3989
Penta | [56, 873, 1950, 962, 69]
```
https://kelseyde.pythonanywhere.com/test/464/
bench 5945241

Return fail medium best score for Q-search fail-high

---

header.sh
src/main/java/com/kelseyde/calvin/search/ParallelSearcher.java
src/main/java/com/kelseyde/calvin/tables/tt/HashEntry.java
src/main/java/com/kelseyde/calvin/tables/tt/TranspositionTable.java
src/test/java/com/kelseyde/calvin/tables/TranspositionTableTest.java

Reverts kelseyde/calvin-chess-engine#335 but also prevents the crashes that have been happening since that was merged. Unfortunately haven't figured out the root cause yet.
```
Elo   | -3.85 +- 3.43 (95%)
LLR   | -2.23 (-2.20, 2.20) [-5.00, 0.00]
Games | N: 11992 W: 2803 L: 2936 D: 6253
Penta | [106, 1499, 2886, 1432, 73]
```
https://kelseyde.pythonanywhere.com/test/472/
bench 6232928

Revert "Compress TT entry to 12 bytes"

---

src/main/java/com/kelseyde/calvin/engine/EngineConfig.java
src/main/java/com/kelseyde/calvin/search/SearchStack.java
src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Elo   | 2.82 +- 2.63 (95%)
LLR   | 2.20 (-2.20, 2.20) [0.00, 5.00]
Games | N: 19608 W: 4710 L: 4551 D: 10347
Penta | [135, 2252, 4862, 2429, 126]
```
https://kelseyde.pythonanywhere.com/test/513/
bench 5046816

Reduce more when previous node fails high

---

src/main/java/com/kelseyde/calvin/engine/EngineConfig.java
src/main/java/com/kelseyde/calvin/search/SearchStack.java
src/main/java/com/kelseyde/calvin/search/Searcher.java

Idea taken from Reckless (in turn taken from Stockfish)
If we reduced the previous node by a lot, and then the static eval indicates the opponent's position improves, correct the reduction in hindsight by extending depth by 1.
```
Elo   | 3.37 +- 3.08 (95%)
LLR   | 2.20 (-2.20, 2.20) [0.00, 5.00]
Games | N: 14120 W: 3393 L: 3256 D: 7471
Penta | [69, 1668, 3480, 1743, 100]
```
https://kelseyde.pythonanywhere.com/test/524/
bench 5421436

Hindsight LMR extension

---

src/main/java/com/kelseyde/calvin/search/Score.java
src/main/java/com/kelseyde/calvin/search/Searcher.java
src/test/java/com/kelseyde/calvin/tables/TranspositionTableTest.java

Instead of initialising scores/evals to `Integer.MIN_VALUE`, use `Score.MIN` instead.
```
Elo   | 0.66 +- 3.02 (95%)
LLR   | 2.20 (-2.20, 2.20) [-5.00, 0.00]
Games | N: 14146 W: 3369 L: 3342 D: 7435
Penta | [66, 1668, 3596, 1659, 84]
```
https://kelseyde.pythonanywhere.com/test/529/
bench 5094420

Clamp all scores to [Score.MIN, Score.MAX] range

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

Passed non-reg.
We were accidentally applying hindsight extensions a second time in singular search. And, we we were accidentally checking the stack staticEval when it was a check node (so the static eval was `Score.MIN`)
```
Elo   | 5.06 +- 5.43 (95%)
LLR   | 2.22 (-2.20, 2.20) [-5.00, 0.00]
Games | N: 4460 W: 1090 L: 1025 D: 2345
Penta | [26, 495, 1123, 560, 26]
```
https://kelseyde.pythonanywhere.com/test/541/
bench 5402845

Don't do hindsight extensions twice, or in check

---

src/main/java/com/kelseyde/calvin/engine/EngineConfig.java
src/main/java/com/kelseyde/calvin/search/SearchHistory.java
src/main/java/com/kelseyde/calvin/search/Searcher.java

Idea from Pawnocchio author @JonathanHallstrom. Reduce less in nodes where the correction history indicates the position is likely complex.
```
Elo   | 9.38 +- 5.93 (95%)
SPRT  | 30.0+0.30s Threads=1 Hash=8MB
LLR   | 2.21 (-2.20, 2.20) [0.00, 5.00]
Games | N: 3262 W: 787 L: 699 D: 1776
Penta | [3, 341, 862, 415, 10]
```
https://kelseyde.pythonanywhere.com/test/560/
bench 6488865

Complexity LMR

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Elo   | 3.52 +- 3.21 (95%)
LLR   | 2.20 (-2.20, 2.20) [0.00, 5.00]
Games | N: 13414 W: 3241 L: 3105 D: 7068
Penta | [92, 1545, 3309, 1657, 104]
```
https://kelseyde.pythonanywhere.com/test/557/
bench 6223457

Do LMR for good noisies in not-ttpv nodes

---

src/main/java/com/kelseyde/calvin/engine/EngineConfig.java
src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Elo   | 6.20 +- 4.78 (95%)
Games | N: 6052 W: 1522 L: 1414 D: 3116
Penta | [40, 678, 1491, 768, 49]
```
https://kelseyde.pythonanywhere.com/test/568/
bench 4821829

Reduce depth on alpha raise

---

src/main/java/com/kelseyde/calvin/engine/EngineConfig.java
src/main/java/com/kelseyde/calvin/search/SearchStack.java
src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/java/com/kelseyde/calvin/tables/history/QuietHistoryTable.java

Idea from Viz (Stockfish)
Use diff between static eval in current node and parent node to improve quiet move ordering
```
Elo   | 6.59 +- 4.57 (95%)
LLR   | 2.21 (-2.20, 2.20) [0.00, 4.00]
Games | N: 6646 W: 1660 L: 1534 D: 3452
Penta | [42, 750, 1626, 850, 55]
```
https://kelseyde.pythonanywhere.com/test/582/
bench 3938982

Dynamic policy move ordering

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

Idea from Reckless.
```
Elo   | 1.99 +- 1.85 (95%)
LLR   | 2.20 (-2.20, 2.20) [0.00, 4.00]
Games | N: 40100 W: 9774 L: 9544 D: 20782
Penta | [266, 4768, 9755, 4992, 269]
```
https://kelseyde.pythonanywhere.com/test/672/

Use static eval in LMP threshold

---

src/main/java/com/kelseyde/calvin/uci/UCI.java
src/main/java/com/kelseyde/calvin/utils/Bench.java

Thanks to @JonathanHallstrom for finally discovering the root cause of Calvin's bench issues. JIT stuff causes the initial call to bench() to slow to a crawl. By re-running a couple times and taking the third result, it produces a more sane NPS output.
bench 3529980

Fix JIT bench slowdown

---

src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/java/com/kelseyde/calvin/utils/Bench.java

Idea from obsidian author gabe.
```
Elo   | 3.41 +- 2.97 (95%)
LLR   | 2.20 (-2.20, 2.20) [0.00, 4.00]
Games | N: 15506 W: 3887 L: 3735 D: 7884
Penta | [113, 1763, 3838, 1937, 102]
```
https://kelseyde.pythonanywhere.com/test/784/
bench 1218894

Don't penalise moves that raise alpha

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Elo   | 2.75 +- 2.50 (95%)
LLR   | 2.21 (-2.20, 2.20) [0.00, 4.00]
Games | N: 21074 W: 5277 L: 5110 D: 10687
Penta | [113, 2443, 5280, 2566, 135]
```
https://chess.n9x.co/test/2248/
bench 1206809

More negative extensions
