kelseyde/calvin-chess-engine

src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Score of Calvin DEV vs Calvin: 401 - 353 - 358  [0.522] 1112
...      Calvin DEV playing White: 208 - 179 - 171  [0.526] 558
...      Calvin DEV playing Black: 193 - 174 - 187  [0.517] 554
...      White vs Black: 382 - 372 - 358  [0.504] 1112
Elo difference: 15.0 +/- 16.8, LOS: 96.0 %, DrawRatio: 32.2 %
```

Return fail-hard score in null-move and futility pruning

---

src/main/java/com/kelseyde/calvin/search/moveordering/MoveOrderer.java

```
Score of Calvin DEV vs Calvin: 415 - 383 - 309  [0.514] 1107
...      Calvin DEV playing White: 223 - 189 - 143  [0.531] 555
...      Calvin DEV playing Black: 192 - 194 - 166  [0.498] 552
...      White vs Black: 417 - 381 - 309  [0.516] 1107
Elo difference: 10.0 +/- 17.4, LOS: 87.1 %, DrawRatio: 27.9 %
```

Always move new killer to the front of the killer table

---

src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/java/com/kelseyde/calvin/search/moveordering/MoveOrderer.java

Fix stalling bug where ply > max killer ply

---

src/main/java/com/kelseyde/calvin/Application.java
src/main/java/com/kelseyde/calvin/search/ParallelSearcher.java
src/main/java/com/kelseyde/calvin/search/Search.java
src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/java/com/kelseyde/calvin/train/TrainingDataScorer.java

Implement scorer to re-score Leela data with Calvin's own search + HCE, for training NNUE

Implement training data scorer 

---

pom.xml
src/main/java/com/kelseyde/calvin/Application.java
src/main/java/com/kelseyde/calvin/engine/EngineInitializer.java

- Add support for infinite go command
- Add support for immediate 'go' command on start with no position specified - engine defaults to startpos

Add support for infinite go command

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Score of Calvin DEV vs Calvin: 313 - 265 - 861  [0.517] 1439
...      Calvin DEV playing White: 221 - 70 - 429  [0.605] 720
...      Calvin DEV playing Black: 92 - 195 - 432  [0.428] 719
...      White vs Black: 416 - 162 - 861  [0.588] 1439
Elo difference: 11.6 +/- 11.4, LOS: 97.7 %, DrawRatio: 59.8 %
```

Dont do IIR in check, and only when tt move is null

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

Score of Calvin DEV vs Calvin: 767 - 710 - 2599  [0.507] 4076
...      Calvin DEV playing White: 619 - 157 - 1262  [0.613] 2038
...      Calvin DEV playing Black: 148 - 553 - 1337  [0.401] 2038
...      White vs Black: 1172 - 305 - 2599  [0.606] 4076
Elo difference: 4.9 +/- 6.4, LOS: 93.1 %, DrawRatio: 63.8 %

Move lmp to before extensions

---

src/main/java/com/kelseyde/calvin/Application.java
src/main/java/com/kelseyde/calvin/evaluation/Score.java
src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Score of Calvin DEV vs Calvin: 210 - 168 - 308  [0.531] 686
...      Calvin DEV playing White: 132 - 58 - 153  [0.608] 343
...      Calvin DEV playing Black: 78 - 110 - 155  [0.453] 343
...      White vs Black: 242 - 136 - 308  [0.577] 686
Elo difference: 21.3 +/- 19.3, LOS: 98.5 %, DrawRatio: 44.9 %
```

Don't expand aspiration window on opposite side

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Score of Calvin DEV vs Calvin: 318 - 232 - 450  [0.543] 1000
...      Calvin DEV playing White: 209 - 73 - 219  [0.636] 501
...      Calvin DEV playing Black: 109 - 159 - 231  [0.450] 499
...      White vs Black: 368 - 182 - 450  [0.593] 1000
Elo difference: 30.0 +/- 16.0, LOS: 100.0 %, DrawRatio: 45.0 %
```

Futility prune before make move, allowing FP for checks

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Score of Calvin DEV vs Calvin: 245 - 204 - 298  [0.527] 747
...      Calvin DEV playing White: 144 - 80 - 150  [0.586] 374
...      Calvin DEV playing Black: 101 - 124 - 148  [0.469] 373
...      White vs Black: 268 - 181 - 298  [0.558] 747
Elo difference: 19.1 +/- 19.3, LOS: 97.3 %, DrawRatio: 39.9 %
```

Always use best move from current depth

---

src/main/java/com/kelseyde/calvin/Application.java
src/main/java/com/kelseyde/calvin/engine/Engine.java
src/main/java/com/kelseyde/calvin/search/ParallelSearcher.java
src/main/java/com/kelseyde/calvin/search/Search.java
src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/java/com/kelseyde/calvin/search/TimeControl.java
src/main/java/com/kelseyde/calvin/search/TimeLimit.java
src/main/java/com/kelseyde/calvin/utils/train/TrainingDataScorer.java
src/test/java/com/kelseyde/calvin/engine/TimeManagementTest.java
src/test/java/com/kelseyde/calvin/puzzles/EndgameTest.java

Stopping early because the concept is sound, will eventually SPSA tune the params
```
Score of Calvin DEV vs Calvin: 489 - 474 - 1480  [0.503] 2443
...      Calvin DEV playing White: 344 - 149 - 729  [0.580] 1222
...      Calvin DEV playing Black: 145 - 325 - 751  [0.426] 1221
...      White vs Black: 669 - 294 - 1480  [0.577] 2443
Elo difference: 2.1 +/- 8.6, LOS: 68.6 %, DrawRatio: 60.6 %
```

Implement tm best move stability

---

src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/java/com/kelseyde/calvin/search/picker/MovePicker.java
src/main/java/com/kelseyde/calvin/search/picker/QuiescentMovePicker.java
src/main/java/com/kelseyde/calvin/search/picker/ScoredMove.java

```
Score of Calvin DEV vs Calvin: 307 - 294 - 1137  [0.504] 1738
...      Calvin DEV playing White: 241 - 67 - 561  [0.600] 869
...      Calvin DEV playing Black: 66 - 227 - 576  [0.407] 869
...      White vs Black: 468 - 133 - 1137  [0.596] 1738
Elo difference: 2.6 +/- 9.6, LOS: 70.2 %, DrawRatio: 65.4 %
```

Optimize move sorting in ```MovePicker```

---

src/main/java/com/kelseyde/calvin/transposition/HashEntry.java
src/main/java/com/kelseyde/calvin/transposition/TranspositionTable.java

```
Score of Calvin DEV vs Calvin: 225 - 199 - 578  [0.513] 1002
...      Calvin DEV playing White: 161 - 60 - 280  [0.601] 501
...      Calvin DEV playing Black: 64 - 139 - 298  [0.425] 501
...      White vs Black: 300 - 124 - 578  [0.588] 1002
Elo difference: 9.0 +/- 14.0, LOS: 89.7 %, DrawRatio: 57.7 %
```

Fix TT mate scores and optimise TT

---

src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/java/com/kelseyde/calvin/search/moveordering/MoveOrderer.java
src/main/java/com/kelseyde/calvin/search/moveordering/MoveOrdering.java

```
Score of Calvin DEV vs Calvin: 290 - 176 - 917  [0.541] 1383
...      Calvin DEV playing White: 221 - 32 - 439  [0.637] 692
...      Calvin DEV playing Black: 69 - 144 - 478  [0.446] 691
...      White vs Black: 365 - 101 - 917  [0.595] 1383
Elo difference: 28.7 +/- 10.6, LOS: 100.0 %, DrawRatio: 66.3 %
```

Add history malus

---

src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/java/com/kelseyde/calvin/search/picker/MovePicker.java
src/main/resources/TODO.md

```
Score of Calvin DEV vs Calvin: 132 - 102 - 438  [0.522] 672
...      Calvin DEV playing White: 92 - 15 - 229  [0.615] 336
...      Calvin DEV playing Black: 40 - 87 - 209  [0.430] 336
...      White vs Black: 179 - 55 - 438  [0.592] 672
Elo difference: 15.5 +/- 15.5, LOS: 97.5 %, DrawRatio: 65.2 %
```

Add ```MovePicker.skipQuiets```

---

src/main/java/com/kelseyde/calvin/evaluation/NNUE.java
src/test/java/com/kelseyde/calvin/evaluation/NNUETest.java

```
Score of Calvin DEV vs Calvin: 315 - 274 - 666  [0.516] 1255
...      Calvin DEV playing White: 231 - 82 - 315  [0.619] 628
...      Calvin DEV playing Black: 84 - 192 - 351  [0.414] 627
...      White vs Black: 423 - 166 - 666  [0.602] 1255
Elo difference: 11.4 +/- 13.2, LOS: 95.4 %, DrawRatio: 53.1 %
```

Add material scaling

---

src/main/java/com/kelseyde/calvin/evaluation/Accumulator.java
src/main/java/com/kelseyde/calvin/evaluation/NNUE.java

Optimise NNUE inference + accumulator updates

---

src/main/java/com/kelseyde/calvin/board/Board.java
src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/java/com/kelseyde/calvin/search/TimeControl.java

Merging early, as it's a tiny change that is implemented in many other engines.
```
Score of Calvin DEV vs Calvin: 268 - 255 - 772  [0.505] 1295
...      Calvin DEV playing White: 202 - 66 - 380  [0.605] 648
...      Calvin DEV playing Black: 66 - 189 - 392  [0.405] 647
...      White vs Black: 391 - 132 - 772  [0.600] 1295
Elo difference: 3.5 +/- 12.0, LOS: 71.5 %, DrawRatio: 59.6 %
```

Only check hard limit every 4096 nodes

---

src/main/java/com/kelseyde/calvin/search/SearchStack.java
src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/java/com/kelseyde/calvin/search/moveordering/MoveOrderer.java
src/main/java/com/kelseyde/calvin/search/moveordering/MoveOrdering.java
src/main/java/com/kelseyde/calvin/tables/history/CounterMoveTable.java

Lost the SPRT, result was +3 +/- 3...

Countermoves

---

src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/resources/engine_config.json
src/test/resources/engine_config.json

```
Score of Calvin DEV vs Calvin: 152 - 116 - 336  [0.530] 604
...      Calvin DEV playing White: 121 - 26 - 155  [0.657] 302
...      Calvin DEV playing Black: 31 - 90 - 181  [0.402] 302
...      White vs Black: 211 - 57 - 336  [0.627] 604
Elo difference: 20.7 +/- 18.4, LOS: 98.6 %, DrawRatio: 55.6 %
```

Use improving heuristic in RFP

---

src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/java/com/kelseyde/calvin/search/moveordering/MoveOrderer.java
src/main/java/com/kelseyde/calvin/search/moveordering/MoveOrdering.java
src/main/java/com/kelseyde/calvin/tables/history/KillerTable.java

```
Score of Calvin DEV vs Calvin: 134 - 98 - 452  [0.526] 684
...      Calvin DEV playing White: 98 - 16 - 229  [0.620] 343
...      Calvin DEV playing Black: 36 - 82 - 223  [0.433] 341
...      White vs Black: 180 - 52 - 452  [0.594] 684
Elo difference: 18.3 +/- 15.1, LOS: 99.1 %, DrawRatio: 66.1 %
```

Clear ply + 1 killers in each node

---

src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/java/com/kelseyde/calvin/search/moveordering/MoveOrderer.java

Woops
```
Score of Calvin DEV vs Calvin: 152 - 121 - 494  [0.520] 767
...      Calvin DEV playing White: 110 - 30 - 244  [0.604] 384
...      Calvin DEV playing Black: 42 - 91 - 250  [0.436] 383
...      White vs Black: 201 - 72 - 494  [0.584] 767
Elo difference: 14.1 +/- 14.6, LOS: 97.0 %, DrawRatio: 64.4 %
```

Clear history table on ucinewgame

---

src/main/java/com/kelseyde/calvin/engine/EngineConfig.java
src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/resources/engine_config.json
src/test/resources/engine_config.json

```
Score of Calvin DEV vs Calvin: 125 - 94 - 540  [0.520] 759
...      Calvin DEV playing White: 101 - 19 - 260  [0.608] 380
...      Calvin DEV playing Black: 24 - 75 - 280  [0.433] 379
...      White vs Black: 176 - 43 - 540  [0.588] 759
Elo difference: 14.2 +/- 13.2, LOS: 98.2 %, DrawRatio: 71.1 %
```

Add fail-high aspiration depth reduction

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Score of Calvin DEV vs Calvin: 172 - 129 - 460  [0.528] 761
...      Calvin DEV playing White: 132 - 35 - 214  [0.627] 381
...      Calvin DEV playing Black: 40 - 94 - 246  [0.429] 380
...      White vs Black: 226 - 75 - 460  [0.599] 761
Elo difference: 19.7 +/- 15.5, LOS: 99.3 %, DrawRatio: 60.4 %
```

Apply malus to all quiets that dont raise alpha

---

src/main/java/com/kelseyde/calvin/search/SearchStack.java
src/main/java/com/kelseyde/calvin/search/Searcher.java
src/test/java/com/kelseyde/calvin/generation/sperft/SPerftTest.java

```
Score of Calvin DEV vs Calvin: 109 - 81 - 268  [0.531] 458
...      Calvin DEV playing White: 83 - 12 - 135  [0.654] 230
...      Calvin DEV playing Black: 26 - 69 - 133  [0.406] 228
...      White vs Black: 152 - 38 - 268  [0.624] 458
Elo difference: 21.3 +/- 20.5, LOS: 97.9 %, DrawRatio: 58.5 %
```

Add isNullMoveAllowed to SearchStack

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

Stopping early as my laptop is about to take off into outer space. Need to invest in better HW for testing:
```
Score of Calvin DEV vs Calvin: 220 - 218 - 654  [0.501] 1092
...      Calvin DEV playing White: 160 - 59 - 327  [0.592] 546
...      Calvin DEV playing Black: 60 - 159 - 327  [0.409] 546
...      White vs Black: 319 - 119 - 654  [0.592] 1092
Elo difference: 0.6 +/- 13.0, LOS: 53.8 %, DrawRatio: 59.9 %
```

Check extension outside of move loop

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Score of Calvin DEV vs Calvin: 192 - 150 - 491  [0.525] 833
...      Calvin DEV playing White: 139 - 51 - 226  [0.606] 416
...      Calvin DEV playing Black: 53 - 99 - 265  [0.445] 417
...      White vs Black: 238 - 104 - 491  [0.580] 833
Elo difference: 17.5 +/- 15.1, LOS: 98.8 %, DrawRatio: 58.9 %
```

Switch to fail-soft in quiescence

---

src/main/java/com/kelseyde/calvin/engine/Engine.java
src/main/java/com/kelseyde/calvin/search/TimeControl.java
src/main/java/com/kelseyde/calvin/uci/UCICommand.java
src/main/java/com/kelseyde/calvin/utils/train/TrainingDataScorer.java
src/test/java/com/kelseyde/calvin/engine/TimeManagementTest.java
src/test/java/com/kelseyde/calvin/puzzles/EndgameTest.java

Also improve train uci command and add hard node limit (default 1mil)

Fix negative time CCRL bug

---

src/main/java/com/kelseyde/calvin/evaluation/NNUE.java
src/main/java/com/kelseyde/calvin/search/SearchHistory.java
src/main/java/com/kelseyde/calvin/search/picker/MovePicker.java

To be continued
```
Score of Calvin DEV vs Calvin: 143 - 129 - 368  [0.511] 640
...      Calvin DEV playing White: 110 - 37 - 174  [0.614] 321
...      Calvin DEV playing Black: 33 - 92 - 194  [0.408] 319
...      White vs Black: 202 - 70 - 368  [0.603] 640
Elo difference: 7.6 +/- 17.5, LOS: 80.2 %, DrawRatio: 57.5 %
```
Will have to add multiple results together, no time to test:
```
Score of Calvin DEV vs Calvin: 540 - 531 - 1590  [0.502] 2661
...      Calvin DEV playing White: 404 - 137 - 790  [0.600] 1331
...      Calvin DEV playing Black: 136 - 394 - 800  [0.403] 1330
...      White vs Black: 798 - 273 - 1590  [0.599] 2661
Elo difference: 1.2 +/- 8.4, LOS: 60.8 %, DrawRatio: 59.8 %
```
Really is just dead equal:
```
Finished game 6355 (Calvin DEV vs Calvin): * {No result}
Score of …
```

1-ply conthist

---

src/main/java/com/kelseyde/calvin/uci/UCI.java
src/main/java/com/kelseyde/calvin/utils/train/TrainingDataScorer.java
src/test/java/com/kelseyde/calvin/puzzles/BlunderTest.java

Training data scorer was crashing when the best move was null, due to already found mate in TT.

Handle null best move

---

pom.xml
src/main/java/com/kelseyde/calvin/uci/UCI.java

Wasn't expecting it to make this much of a difference...
```
Score of Calvin DEV vs Calvin: 228 - 159 - 613  [0.534] 1000
...      Calvin DEV playing White: 178 - 29 - 293  [0.649] 500
...      Calvin DEV playing Black: 50 - 130 - 320  [0.420] 500
...      White vs Black: 308 - 79 - 613  [0.615] 1000
Elo difference: 24.0 +/- 13.4, LOS: 100.0 %, DrawRatio: 61.3 %
```

Call garbage collector on ucinewgame

---

src/main/java/com/kelseyde/calvin/search/SearchHistory.java
src/main/java/com/kelseyde/calvin/search/SearchStack.java
src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/java/com/kelseyde/calvin/search/picker/MovePicker.java

```
Score of Calvin DEV vs Calvin: 391 - 317 - 1086  [0.521] 1794
...      Calvin DEV playing White: 297 - 85 - 515  [0.618] 897
...      Calvin DEV playing Black: 94 - 232 - 571  [0.423] 897
...      White vs Black: 529 - 179 - 1086  [0.598] 1794
Elo difference: 14.3 +/- 10.1, LOS: 99.7 %, DrawRatio: 60.5 %
```

Only update quiet history scores on fail-high

---

src/main/java/com/kelseyde/calvin/search/SearchHistory.java
src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Score of Calvin DEV vs Calvin: 154 - 121 - 329  [0.527] 604
...      Calvin DEV playing White: 116 - 28 - 159  [0.645] 303
...      Calvin DEV playing Black: 38 - 93 - 170  [0.409] 301
...      White vs Black: 209 - 66 - 329  [0.618] 604
Elo difference: 19.0 +/- 18.7, LOS: 97.7 %, DrawRatio: 54.5 %
```

Only update capthist on fail high

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

Needs more testing
```
Score of Calvin DEV vs Calvin: 114 - 103 - 323  [0.510] 540
...      Calvin DEV playing White: 86 - 29 - 155  [0.606] 270
...      Calvin DEV playing Black: 28 - 74 - 168  [0.415] 270
...      White vs Black: 160 - 57 - 323  [0.595] 540
Elo difference: 7.1 +/- 18.6, LOS: 77.2 %, DrawRatio: 59.8 %
```
Edit: more testing:
```
Score of Calvin DEV vs Calvin: 552 - 520 - 1379  [0.507] 2451
...      Calvin DEV playing White: 382 - 151 - 693  [0.594] 1226
...      Calvin DEV playing Black: 170 - 369 - 686  [0.419] 1225
...      White vs Black: 751 - 321 - 1379  [0.588] 2451
Elo difference: 4.5 +/- 9.1, LOS: 83.6 %, DrawRatio: 56.3 %
```
Combined:
+4 +/- 8

Allow check extension at depth 1

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Score of Calvin DEV vs Calvin: 465 - 397 - 959  [0.519] 1821
...      Calvin DEV playing White: 329 - 122 - 460  [0.614] 911
...      Calvin DEV playing Black: 136 - 275 - 499  [0.424] 910
...      White vs Black: 604 - 258 - 959  [0.595] 1821
Elo difference: 13.0 +/- 11.0, LOS: 99.0 %, DrawRatio: 52.7 %
```

Return (staticEval + beta) / 2 in RFP

---

src/main/java/com/kelseyde/calvin/engine/Engine.java
src/main/java/com/kelseyde/calvin/uci/UCI.java
src/main/java/com/kelseyde/calvin/uci/UCICommand.java
src/main/java/com/kelseyde/calvin/utils/Bench.java
src/main/java/com/kelseyde/calvin/utils/perft/PerftService.java
src/test/java/com/kelseyde/calvin/movegen/perft/PerftTest.java

Quick reg test:
```
Score of Calvin DEV vs Calvin: 204 - 216 - 681  [0.495] 1101
...      Calvin DEV playing White: 163 - 50 - 338  [0.603] 551
...      Calvin DEV playing Black: 41 - 166 - 343  [0.386] 550
...      White vs Black: 329 - 91 - 681  [0.608] 1101
Elo difference: -3.8 +/- 12.7, LOS: 27.9 %, DrawRatio: 61.9 %
```

Add perft to UCI

---

src/main/java/com/kelseyde/calvin/engine/Engine.java
src/main/java/com/kelseyde/calvin/engine/EngineConfig.java
src/main/java/com/kelseyde/calvin/search/TimeControl.java
src/main/java/com/kelseyde/calvin/utils/Bench.java
src/main/java/com/kelseyde/calvin/utils/train/TrainingDataScorer.java
src/test/java/com/kelseyde/calvin/puzzles/BlunderTest.java
src/test/java/com/kelseyde/calvin/puzzles/EndgameTest.java

Make time management params tunable 

---

src/main/java/com/kelseyde/calvin/tables/history/KillerTable.java

After fixing duplicate killers:
```
Score of Calvin DEV vs Calvin: 348 - 331 - 672  [0.506] 1351
...      Calvin DEV playing White: 273 - 71 - 332  [0.649] 676
...      Calvin DEV playing Black: 75 - 260 - 340  [0.363] 675
...      White vs Black: 533 - 146 - 672  [0.643] 1351
Elo difference: 4.4 +/- 13.1, LOS: 74.3 %, DrawRatio: 49.7 %
```

Killer bug

---

src/main/java/com/kelseyde/calvin/tables/history/KillerTable.java

```
Score of Calvin DEV vs Calvin: 467 - 458 - 1077  [0.502] 2002
...      Calvin DEV playing White: 373 - 90 - 539  [0.641] 1002
...      Calvin DEV playing Black: 94 - 368 - 538  [0.363] 1000
...      White vs Black: 741 - 184 - 1077  [0.639] 2002
Elo difference: 1.6 +/- 10.3, LOS: 61.6 %, DrawRatio: 53.8 %
```

Remove third killer move

---

src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/java/com/kelseyde/calvin/utils/train/TrainingDataScorer.java

```
Score of Calvin DEV vs Calvin: 1369 - 1244 - 2147  [0.513] 4760
...      Calvin DEV playing White: 1038 - 279 - 1063  [0.659] 2380
...      Calvin DEV playing Black: 331 - 965 - 1084  [0.367] 2380
...      White vs Black: 2003 - 610 - 2147  [0.646] 4760
Elo difference: 9.1 +/- 7.3, LOS: 99.3 %, DrawRatio: 45.1 %
```

Capture LMR

---

src/main/java/com/kelseyde/calvin/engine/Engine.java
src/main/java/com/kelseyde/calvin/uci/Pretty.java
src/main/java/com/kelseyde/calvin/uci/UCI.java
src/main/java/com/kelseyde/calvin/uci/UCICommandType.java

Add pretty print

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Score of Calvin DEV vs Calvin: 2450 - 2385 - 5165  [0.503] 10000
...      Calvin DEV playing White: 1962 - 497 - 2541  [0.646] 5000
...      Calvin DEV playing Black: 488 - 1888 - 2624  [0.360] 5000
...      White vs Black: 3850 - 985 - 5165  [0.643] 10000
Elo difference: 2.3 +/- 4.7, LOS: 82.5 %, DrawRatio: 51.6 %
```

Increase history depth if staticEval > alpha

---

src/main/java/com/kelseyde/calvin/engine/EngineConfig.java
src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/java/com/kelseyde/calvin/tables/history/AbstractHistoryTable.java
src/main/java/com/kelseyde/calvin/tables/history/CaptureHistoryTable.java
src/main/java/com/kelseyde/calvin/tables/history/ContinuationHistoryTable.java
src/main/java/com/kelseyde/calvin/tables/history/QuietHistoryTable.java

Accidentally deleted the SPRT... it was around +8 +/- 7.

Linear history bonuses

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Score of Calvin DEV vs Calvin: 4897 - 4756 - 11555  [0.503] 21208
...      Calvin DEV playing White: 4021 - 813 - 5770  [0.651] 10604
...      Calvin DEV playing Black: 876 - 3943 - 5785  [0.355] 10604
...      White vs Black: 7964 - 1689 - 11555  [0.648] 21208
Elo difference: 2.3 +/- 3.2, LOS: 92.4 %, DrawRatio: 54.5 %
```

Dont TT cut in QS PV nodes

---

src/main/java/com/kelseyde/calvin/search/SearchHistory.java
src/main/java/com/kelseyde/calvin/search/SearchStack.java
src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/java/com/kelseyde/calvin/search/picker/MovePicker.java
src/test/java/com/kelseyde/calvin/search/picker/MovePickerTest.java
src/test/java/com/kelseyde/calvin/tables/ContHistTableTest.java

Another minorest of minor speedups
Quick regtest:
```
Score of Calvin DEV vs Calvin: 302 - 298 - 400  [0.502] 1000
...      Calvin DEV playing White: 216 - 85 - 198  [0.631] 499
...      Calvin DEV playing Black: 86 - 213 - 202  [0.373] 501
...      White vs Black: 429 - 171 - 400  [0.629] 1000
Elo difference: 1.4 +/- 16.7, LOS: 56.5 %, DrawRatio: 40.0 %
```

Only retrieve SearchStackEntry once per ply

---

src/main/java/com/kelseyde/calvin/search/PlayedMove.java
src/main/java/com/kelseyde/calvin/search/SearchHistory.java
src/main/java/com/kelseyde/calvin/search/SearchStack.java
src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/java/com/kelseyde/calvin/search/picker/MovePicker.java
src/test/java/com/kelseyde/calvin/tables/ContHistTableTest.java

After merging quietsSearched and capturesSearched into one list (just confirming I didn't break anything):
```
Score of Calvin DEV vs Calvin: 1439 - 1367 - 2581  [0.507] 5387
...      Calvin DEV playing White: 1077 - 335 - 1281  [0.638] 2693
...      Calvin DEV playing Black: 362 - 1032 - 1300  [0.376] 2694
...      White vs Black: 2109 - 697 - 2581  [0.631] 5387
Elo difference: 4.6 +/- 6.7, LOS: 91.3 %, DrawRatio: 47.9 %
```

Refactor history updates

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Score of Calvin DEV vs Calvin: 2320 - 2215 - 4633  [0.506] 9168
...      Calvin DEV playing White: 1843 - 480 - 2262  [0.649] 4585
...      Calvin DEV playing Black: 477 - 1735 - 2371  [0.363] 4583
...      White vs Black: 3578 - 957 - 4633  [0.643] 9168
Elo difference: 4.0 +/- 5.0, LOS: 94.1 %, DrawRatio: 50.5 %
```

Remove depth 1 checks in q search

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

Minor speedup, since we now know whether a move is quiet before making it on the board, updating NNUE etc.
Quick regtest:
```
Score of Calvin DEV vs Calvin: 816 - 804 - 1470  [0.502] 3090
...      Calvin DEV playing White: 622 - 193 - 730  [0.639] 1545
...      Calvin DEV playing Black: 194 - 611 - 740  [0.365] 1545
...      White vs Black: 1233 - 387 - 1470  [0.637] 3090
Elo difference: 1.3 +/- 8.9, LOS: 61.7 %, DrawRatio: 47.6 %
```

LMP before makeMove

---

src/main/java/com/kelseyde/calvin/search/picker/MovePicker.java

Non-functional:
```
Score of Calvin DEV vs Calvin: 1706 - 1710 - 3591  [0.500] 7007
...      Calvin DEV playing White: 1376 - 343 - 1785  [0.647] 3504
...      Calvin DEV playing Black: 330 - 1367 - 1806  [0.352] 3503
...      White vs Black: 2743 - 673 - 3591  [0.648] 7007
Elo difference: -0.2 +/- 5.7, LOS: 47.3 %, DrawRatio: 51.2 %
```

Tidy up MovePicker

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Score of Calvin DEV vs Calvin: 849 - 716 - 1216  [0.524] 2781
...      Calvin DEV playing White: 610 - 177 - 605  [0.656] 1392
...      Calvin DEV playing Black: 239 - 539 - 611  [0.392] 1389
...      White vs Black: 1149 - 416 - 1216  [0.632] 2781
Elo difference: 16.6 +/- 9.7, LOS: 100.0 %, DrawRatio: 43.7 %
SPRT: llr 2.9 (100.2%), lbound -2.25, ubound 2.89 - H1 was accepted
```

Write to the TT in Q-search

---

src/main/java/com/kelseyde/calvin/board/Board.java
src/main/java/com/kelseyde/calvin/engine/Engine.java
src/main/java/com/kelseyde/calvin/search/ParallelSearcher.java

Merging early because the dev stopped making illegal moves when hitting max ply.
```
Score of Calvin DEV vs Calvin: 247 - 212 - 791  [0.514] 1250
...      Calvin DEV playing White: 197 - 42 - 386  [0.624] 625
...      Calvin DEV playing Black: 50 - 170 - 405  [0.404] 625
...      White vs Black: 367 - 92 - 791  [0.610] 1250
Elo difference: 9.7 +/- 11.7, LOS: 94.9 %, DrawRatio: 63.3 %
```

Dont increment ply when applying uci moves

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Score of Calvin DEV vs Calvin: 2169 - 2061 - 4770  [0.506] 9000
...      Calvin DEV playing White: 1796 - 364 - 2341  [0.659] 4501
...      Calvin DEV playing Black: 373 - 1697 - 2429  [0.353] 4499
...      White vs Black: 3493 - 737 - 4770  [0.653] 9000
Elo difference: 4.2 +/- 4.9, LOS: 95.2 %, DrawRatio: 53.0 %
```

Remove NMP margin

---

src/main/java/com/kelseyde/calvin/engine/Engine.java
src/main/java/com/kelseyde/calvin/search/SearchResult.java
src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/java/com/kelseyde/calvin/search/ThreadData.java
src/main/java/com/kelseyde/calvin/search/TimeControl.java
src/main/java/com/kelseyde/calvin/utils/train/TrainingDataScorer.java
src/test/java/com/kelseyde/calvin/puzzles/BlunderTest.java
src/test/java/com/kelseyde/calvin/puzzles/EndgameTest.java

Merging early as there are no more time losses at STC:
```
Score of Calvin DEV vs Calvin: 662 - 611 - 907  [0.512] 2180
...      Calvin DEV playing White: 479 - 152 - 460  [0.650] 1091
...      Calvin DEV playing Black: 183 - 459 - 447  [0.373] 1089
...      White vs Black: 938 - 335 - 907  [0.638] 2180
Elo difference: 8.1 +/- 11.1, LOS: 92.4 %, DrawRatio: 41.6 %
```

Start clock as soon as 'go' command is received

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

Minor minor minor speedup.
```
Score of Calvin DEV vs Calvin: 1572 - 1532 - 2896  [0.503] 6000
...      Calvin DEV playing White: 1258 - 330 - 1413  [0.655] 3001
...      Calvin DEV playing Black: 314 - 1202 - 1483  [0.352] 2999
...      White vs Black: 2460 - 644 - 2896  [0.651] 6000
Elo difference: 2.3 +/- 6.3, LOS: 76.4 %, DrawRatio: 48.3 %
```

Initialise `MovePicker` after stand-pat cutoff

---

src/main/java/com/kelseyde/calvin/engine/EngineConfig.java
src/main/java/com/kelseyde/calvin/search/TimeControl.java

```
Score of Calvin DEV vs Calvin: 1067 - 972 - 1396  [0.514] 3435
...      Calvin DEV playing White: 782 - 253 - 683  [0.654] 1718
...      Calvin DEV playing Black: 285 - 719 - 713  [0.374] 1717
...      White vs Black: 1501 - 538 - 1396  [0.640] 3435
Elo difference: 9.6 +/- 8.9, LOS: 98.2 %, DrawRatio: 40.6 %
SPRT: llr 2.9 (100.5%), lbound -2.25, ubound 2.89 - H1 was accepted
```

Make time management constant tunable

---

src/main/java/com/kelseyde/calvin/search/picker/MovePicker.java

```
Score of Calvin DEV vs Calvin: 1761 - 1606 - 2761  [0.513] 6128
...      Calvin DEV playing White: 1309 - 385 - 1371  [0.651] 3065
...      Calvin DEV playing Black: 452 - 1221 - 1390  [0.374] 3063
...      White vs Black: 2530 - 837 - 2761  [0.638] 6128
Elo difference: 8.8 +/- 6.4, LOS: 99.6 %, DrawRatio: 45.1 %
SPRT: llr 2.91 (100.6%), lbound -2.25, ubound 2.89 - H1 was accepted
```

Use capthist score in SEE threshold

---

src/main/java/com/kelseyde/calvin/engine/EngineConfig.java
src/main/java/com/kelseyde/calvin/search/SearchHistory.java
src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/java/com/kelseyde/calvin/search/picker/MovePicker.java
src/main/java/com/kelseyde/calvin/search/picker/QuiescentMovePicker.java
src/test/java/com/kelseyde/calvin/search/picker/MovePickerTest.java

nonreg:
```
Score of Calvin DEV vs Calvin: 1108 - 1051 - 1663  [0.507] 3822
...      Calvin DEV playing White: 796 - 271 - 844  [0.637] 1911
...      Calvin DEV playing Black: 312 - 780 - 819  [0.378] 1911
...      White vs Black: 1576 - 583 - 1663  [0.630] 3822
Elo difference: 5.2 +/- 8.3, LOS: 89.0 %, DrawRatio: 43.5 %
```

Make `MovePicker` variables tunable

---

src/main/java/com/kelseyde/calvin/search/PlayedMove.java
src/main/java/com/kelseyde/calvin/search/SearchHistory.java
src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/java/com/kelseyde/calvin/search/picker/MovePicker.java
src/test/java/com/kelseyde/calvin/tables/ContHistTableTest.java

Non-reg:
```
Score of Calvin DEV vs Calvin: 2099 - 2093 - 3105  [0.500] 7297
...      Calvin DEV playing White: 1573 - 521 - 1554  [0.644] 3648
...      Calvin DEV playing Black: 526 - 1572 - 1551  [0.357] 3649
...      White vs Black: 3145 - 1047 - 3105  [0.644] 7297
Elo difference: 0.3 +/- 6.0, LOS: 53.7 %, DrawRatio: 42.6 %
```

Tidy up SearchHistory

---

src/main/java/com/kelseyde/calvin/search/SearchHistory.java
src/main/java/com/kelseyde/calvin/search/Searcher.java

Merging early since all engines do it this way.
```
Finished game 2070 (Calvin vs Calvin DEV): 1-0 {Black loses on time}
Score of Calvin DEV vs Calvin: 623 - 617 - 834  [0.501] 2074
...      Calvin DEV playing White: 456 - 164 - 417  [0.641] 1037
...      Calvin DEV playing Black: 167 - 453 - 417  [0.362] 1037
...      White vs Black: 909 - 331 - 834  [0.639] 2074
Elo difference: 1.0 +/- 11.5, LOS: 56.8 %, DrawRatio: 40.2 %
```

Only update history when bestScore >= beta

---

src/main/java/com/kelseyde/calvin/board/Board.java
src/main/java/com/kelseyde/calvin/board/Piece.java
src/main/java/com/kelseyde/calvin/utils/notation/FEN.java

Quick non-reg:
```
Score of Calvin DEV vs Calvin: 369 - 360 - 503  [0.504] 1232
...      Calvin DEV playing White: 258 - 101 - 257  [0.627] 616
...      Calvin DEV playing Black: 111 - 259 - 246  [0.380] 616
...      White vs Black: 517 - 212 - 503  [0.624] 1232
Elo difference: 2.5 +/- 14.9, LOS: 63.1 %, DrawRatio: 40.8 %
```

Replace Board piece bbs with single bb array

---

src/main/java/com/kelseyde/calvin/evaluation/Accumulator.java
src/main/java/com/kelseyde/calvin/evaluation/Feature.java
src/main/java/com/kelseyde/calvin/evaluation/NNUE.java

Merging as this will be the groundwork for finally implementing lazy updates.
```
Score of Calvin DEV vs Calvin: 2467 - 2487 - 4147  [0.499] 9101
...      Calvin DEV playing White: 1877 - 628 - 2046  [0.637] 4551
...      Calvin DEV playing Black: 590 - 1859 - 2101  [0.361] 4550
...      White vs Black: 3736 - 1218 - 4147  [0.638] 9101
Elo difference: -0.8 +/- 5.3, LOS: 38.8 %, DrawRatio: 45.6 %
```

Refactor accumulator feature updates

---

src/main/java/com/kelseyde/calvin/board/Board.java
src/main/java/com/kelseyde/calvin/engine/Engine.java

```
Score of Calvin DEV vs Calvin: 2002 - 1842 - 3543  [0.511] 7387
...      Calvin DEV playing White: 1435 - 519 - 1739  [0.624] 3693
...      Calvin DEV playing Black: 567 - 1323 - 1804  [0.398] 3694
...      White vs Black: 2758 - 1086 - 3543  [0.613] 7387
Elo difference: 7.5 +/- 5.7, LOS: 99.5 %, DrawRatio: 48.0 %
SPRT: llr 2.96 (100.4%), lbound -2.94, ubound 2.94 - H1 was accepted
```

Include positions before root in repetition detection

---

src/main/java/com/kelseyde/calvin/evaluation/Accumulator.java
src/main/java/com/kelseyde/calvin/evaluation/NNUE.java

Non-functional refactor.
Non-reg:
```
Score of Calvin DEV vs Calvin: 846 - 844 - 1310  [0.500] 3000
...      Calvin DEV playing White: 598 - 231 - 671  [0.622] 1500
...      Calvin DEV playing Black: 248 - 613 - 639  [0.378] 1500
...      White vs Black: 1211 - 479 - 1310  [0.622] 3000
Elo difference: 0.2 +/- 9.3, LOS: 51.9 %, DrawRatio: 43.7 %
```

Refactor NNUE code

---

src/main/java/com/kelseyde/calvin/board/Key.java
src/main/java/com/kelseyde/calvin/search/picker/MovePicker.java
src/main/java/com/kelseyde/calvin/search/picker/MoveScorer.java

Non-functional, bench unchanged.

Refactor MovePicker, add MoveScorer

---

src/main/java/com/kelseyde/calvin/evaluation/activation/Screlu.java
src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/java/com/kelseyde/calvin/tables/tt/HashEntry.java
src/main/java/com/kelseyde/calvin/tables/tt/HashFlag.java
src/main/java/com/kelseyde/calvin/tables/tt/TranspositionTable.java
src/test/java/com/kelseyde/calvin/tables/TranspositionTableTest.java

Bench unchanged. Minor nps bump.

Minor speed refactorings

---

src/main/java/com/kelseyde/calvin/engine/Engine.java
src/main/java/com/kelseyde/calvin/search/TimeControl.java
src/main/java/com/kelseyde/calvin/uci/UCI.java
src/main/java/com/kelseyde/calvin/utils/Bench.java

Just merging as it stopped losing on time frequently in STC games.
```
Score of Calvin DEV vs Calvin: 1910 - 1934 - 3156  [0.498] 7000
...      Calvin DEV playing White: 1459 - 449 - 1592  [0.644] 3500
...      Calvin DEV playing Black: 451 - 1485 - 1564  [0.352] 3500
...      White vs Black: 2944 - 900 - 3156  [0.646] 7000
Elo difference: -1.2 +/- 6.0, LOS: 34.9 %, DrawRatio: 45.1 %
```

Fix time losses

---

src/main/java/com/kelseyde/calvin/search/Searcher.java
src/test/java/com/kelseyde/calvin/movegen/Chess960Test.java
src/test/java/com/kelseyde/calvin/movegen/sperft/SPerftTest.java

```
Elo   | 6.40 +- 4.84 (95%)
Games | N: 6026 W: 1472 L: 1361 D: 3193
Penta | [37, 693, 1462, 764, 57]
```

Cut-node IIR

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Elo   | 3.67 +- 3.40 (95%)
LLR   | 2.09 (-2.89, 2.25) [0.00, 5.00]
Games | N: 12218 W: 2905 L: 2776 D: 6537
Penta | [97, 1415, 2954, 1548, 95]
```
bench 551438

Use `cutnode` in TT cut-off condition

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Elo   | 4.32 +- 3.70 (95%)
Games | N: 10380 W: 2503 L: 2374 D: 5503
Penta | [90, 1160, 2569, 1273, 98]
```
bench 5875098

Use TT hit info in NMP

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Elo   | 6.95 +- 5.10 (95%)
LLR   | 2.30 (-2.89, 2.25) [0.00, 5.00]
Games | N: 5648 W: 1354 L: 1241 D: 3053
Penta | [52, 628, 1354, 735, 55]
```
https://kelseyde.pythonanywhere.com/test/30/
bench 4387940

Don't drop into Q-search in check

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

STC:
```
Elo   | 3.88 +- 3.41 (95%)
LLR   | 2.31 (-2.89, 2.25) [0.00, 5.00]
Games | N: 12812 W: 3087 L: 2944 D: 6781
Penta | [116, 1515, 3006, 1648, 121]
```
https://kelseyde.pythonanywhere.com/test/72/
bench 4627069

Dont prune in rootNode

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

STC:
```
Elo   | 4.69 +- 3.94 (95%)
Games | N: 9118 W: 2178 L: 2055 D: 4885
Penta | [62, 1068, 2192, 1159, 78]
```
https://kelseyde.pythonanywhere.com/test/77/
bench 4503768

Tweak RFP return value

---

src/main/java/com/kelseyde/calvin/engine/EngineConfig.java
src/main/java/com/kelseyde/calvin/search/Searcher.java

Weights yoinked from Integral (thank u)
STC:
```
Elo   | 8.12 +- 5.60 (95%)
LLR   | 2.27 (-2.89, 2.25) [0.00, 5.00]
Games | N: 4496 W: 1097 L: 992 D: 2407
Penta | [39, 479, 1104, 590, 36]
```
https://kelseyde.pythonanywhere.com/test/78/
bench 4512179

Try new fp formula

---

src/main/java/com/kelseyde/calvin/engine/EngineConfig.java
src/main/java/com/kelseyde/calvin/search/picker/MovePicker.java
src/main/java/com/kelseyde/calvin/search/picker/MoveScorer.java
src/main/java/com/kelseyde/calvin/search/picker/QuiescentMovePicker.java

Non-functional. Preparing for an SPSA tune.
bench 5075540

Separate tunable params for see noisy offset/divisor in PVS and QS

---

src/main/java/com/kelseyde/calvin/engine/EngineConfig.java
src/main/java/com/kelseyde/calvin/search/Searcher.java

Non-functional for now, will be SPSA tuned.
```
Elo   | -0.28 +- 3.64 (95%)
LLR   | 0.82 (-2.89, 2.25) [-5.00, 0.00]
Games | N: 10014 W: 2301 L: 2309 D: 5404
Penta | [71, 1144, 2596, 1114, 82]
```
https://kelseyde.pythonanywhere.com/test/130/
bench 5075540

Set up fractional LMR

---

src/main/java/com/kelseyde/calvin/engine/EngineConfig.java
src/main/java/com/kelseyde/calvin/search/SearchHistory.java
src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/java/com/kelseyde/calvin/search/TimeControl.java
src/main/java/com/kelseyde/calvin/search/picker/MovePicker.java
src/main/java/com/kelseyde/calvin/search/picker/MoveScorer.java
src/main/java/com/kelseyde/calvin/search/picker/QuiescentMovePicker.java
src/main/java/com/kelseyde/calvin/tables/history/CaptureHistoryTable.java
src/main/java/com/kelseyde/calvin/tables/history/ContinuationHistoryTable.java
src/main/java/com/kelseyde/calvin/tables/history/QuietHistoryTable.java

Non-functional, just tidying up the code a bit.
bench 5779060

Make tunables private

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

This was run as non-reg but heck it might even gain elo:
```
Elo   | 6.34 +- 5.95 (95%)
LLR   | 2.28 (-2.89, 2.25) [-5.00, 0.00]
Games | N: 3894 W: 953 L: 882 D: 2059
Penta | [30, 418, 986, 477, 36]
```
https://kelseyde.pythonanywhere.com/test/140/
bench 5680244

Remove FP futility reductions

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Elo   | 3.58 +- 3.18 (95%)
LLR   | 2.30 (-2.89, 2.25) [0.00, 5.00]
Games | N: 13986 W: 3256 L: 3112 D: 7618
Penta | [101, 1641, 3387, 1741, 123]
```
https://kelseyde.pythonanywhere.com/test/160/
bench 4517518

Write to TT in Q-search standpat cutoff

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Elo   | 6.98 +- 5.08 (95%)
LLR   | 2.27 (-2.89, 2.25) [0.00, 5.00]
Games | N: 5328 W: 1259 L: 1152 D: 2917
Penta | [38, 583, 1318, 684, 41]
```
https://kelseyde.pythonanywhere.com/test/172/
bench 4502629

Correctly update current move in search stack

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Elo   | 4.00 +- 3.49 (95%)
Games | N: 11370 W: 2599 L: 2468 D: 6303
Penta | [84, 1298, 2784, 1441, 78]
```
https://kelseyde.pythonanywhere.com/test/251/
bench 4861735

Negative extensions

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

Refactor search

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Elo   | 4.65 +- 3.89 (95%)
LLR   | 2.29 (-2.89, 2.25) [0.00, 5.00]
Games | N: 9420 W: 2276 L: 2150 D: 4994
Penta | [79, 1062, 2309, 1174, 86]
```
https://kelseyde.pythonanywhere.com/test/290/
bench 4884931

Double negative extensions

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Elo   | 21.97 +- 9.66 (95%)
LLR   | 2.32 (-2.89, 2.25) [0.00, 5.00]
Games | N: 1520 W: 405 L: 309 D: 806
Penta | [9, 143, 368, 223, 17]
```
https://kelseyde.pythonanywhere.com/test/295/
bench 4975170

Do IIR when TT depth is shallow

---

src/main/java/com/kelseyde/calvin/search/picker/MoveScorer.java

```
Elo   | 4.98 +- 4.08 (95%)
Games | N: 8304 W: 2024 L: 1905 D: 4375
Penta | [55, 949, 2035, 1048, 65]
```
https://kelseyde.pythonanywhere.com/test/352/
bench 3947307

Add conthist to search history score

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

Bench unchanged.
bench 4610022

Handle no legal moves at root

---

src/main/java/com/kelseyde/calvin/board/Board.java
src/main/java/com/kelseyde/calvin/search/picker/MovePicker.java

```
Elo   | 0.89 +- 3.27 (95%)
LLR   | 2.21 (-2.20, 2.20) [-5.00, 0.00]
Games | N: 12912 W: 3035 L: 3002 D: 6875
Penta | [86, 1562, 3129, 1591, 88]
```
https://kelseyde.pythonanywhere.com/test/365/
bench 4703635

Stop allowing noisy killers

---

src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/java/com/kelseyde/calvin/search/ThreadData.java

```
Elo   | 3.00 +- 4.40 (95%)
LLR   | 2.22 (-2.20, 2.20) [-5.00, 0.00]
Games | N: 6492 W: 1526 L: 1470 D: 3496
Penta | [32, 719, 1691, 769, 35]
```
https://kelseyde.pythonanywhere.com/test/368/
bench 4703635

NMP verification search

---

src/main/java/com/kelseyde/calvin/evaluation/activation/Screlu.java

Thanks to Serendipity author shawn_xu for the suggestion
```
Elo   | 12.27 +- 8.26 (95%)
SPRT  | 4.0+0.04s Threads=1 Hash=8MB
LLR   | 2.21 (-2.20, 2.20) [-5.00, 0.00]
Games | N: 2238 W: 587 L: 508 D: 1143
Penta | [19, 245, 520, 308, 27]
```
https://kelseyde.pythonanywhere.com/test/388/
bench 4791019

Screlu speedup

---

src/main/java/com/kelseyde/calvin/evaluation/Accumulator.java
src/main/java/com/kelseyde/calvin/evaluation/NNUE.java
src/test/java/com/kelseyde/calvin/evaluation/NNUETest.java

```
Elo   | 22.33 +- 11.10 (95%)
SPRT  | 4.0+0.04s Threads=1 Hash=8MB
LLR   | 2.20 (-2.20, 2.20) [-5.00, 0.00]
Games | N: 1340 W: 374 L: 288 D: 678
Penta | [14, 128, 313, 188, 27]
```
https://kelseyde.pythonanywhere.com/test/423/
bench 4704922

Use SIMD for accumulator copies

---

src/main/java/com/kelseyde/calvin/engine/EngineConfig.java
src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Elo   | 2.57 +- 2.40 (95%)
LLR   | 2.20 (-2.20, 2.20) [0.00, 5.00]
Games | N: 23374 W: 5660 L: 5487 D: 12227
Penta | [164, 2638, 5923, 2785, 177]
````
https://kelseyde.pythonanywhere.com/test/436/
bench 5250336

Reduce aspiration window widening factor

---

src/main/java/com/kelseyde/calvin/evaluation/NNUE.java
src/main/java/com/kelseyde/calvin/evaluation/Network.java

```
Elo   | 11.50 +- 6.97 (95%)
LLR   | 2.24 (-2.20, 2.20) [0.00, 5.00]
Games | N: 3022 W: 826 L: 726 D: 1470
Penta | [25, 325, 715, 417, 29]
```
https://kelseyde.pythonanywhere.com/test/479/
bench 5778639

New net, same arch, add feature factoriser

---

src/main/java/com/kelseyde/calvin/evaluation/NNUE.java

```
Elo   | 8.60 +- 5.97 (95%)
LLR   | 2.21 (-2.20, 2.20) [0.00, 5.00]
Games | N: 4244 W: 1175 L: 1070 D: 1999
Penta | [29, 492, 1007, 533, 61]
```
https://kelseyde.pythonanywhere.com/test/487/
bench 5989643

New net, 6 input buckets

---

src/main/java/com/kelseyde/calvin/evaluation/NNUE.java

```
Elo   | 5.48 +- 4.49 (95%)
Games | N: 7544 W: 1957 L: 1838 D: 3749
Penta | [65, 884, 1786, 941, 96]
```
https://kelseyde.pythonanywhere.com/test/491/
bench 5936171

New net, 8 input buckets

---

src/main/java/com/kelseyde/calvin/engine/EngineConfig.java
src/main/java/com/kelseyde/calvin/search/Searcher.java

Non-functional. To be tuned later in SPSA.
bench 5046816

Make RFP improving margin tunable

---

src/main/java/com/kelseyde/calvin/evaluation/Accumulator.java
src/main/java/com/kelseyde/calvin/evaluation/NNUE.java

Credit to pawnocchio author swedishchef.
Small speedup. Passed non-reg:
```
Elo   | 0.86 +- 3.40 (95%)
SPRT  | 3.0+0.03s Threads=1 Hash=8MB
LLR   | 2.20 (-2.20, 2.20) [-5.00, 0.00]
Games | N: 13276 W: 3387 L: 3354 D: 6535
Penta | [175, 1495, 3252, 1554, 162]
```
https://kelseyde.pythonanywhere.com/test/526/
bench 5046816

Fused accumulator refreshes

---

src/main/java/com/kelseyde/calvin/board/Bits.java
src/main/java/com/kelseyde/calvin/movegen/Attacks.java
src/main/java/com/kelseyde/calvin/movegen/MoveGenerator.java
src/test/java/com/kelseyde/calvin/board/CheckTest.java

Allows us to check if a move gives check before the move is made.
bench 5094420

Add `givesCheck` function

---

src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Elo   | 8.03 +- 5.81 (95%)
LLR   | 2.20 (-2.20, 2.20) [-4.00, 0.00]
Games | N: 3894 W: 963 L: 873 D: 2058
Penta | [20, 424, 972, 508, 23]
````
https://kelseyde.pythonanywhere.com/test/586/
bench 3985086

Re-write principal variation search

---

src/main/java/com/kelseyde/calvin/board/Board.java
src/main/java/com/kelseyde/calvin/movegen/MoveGenerator.java
src/main/java/com/kelseyde/calvin/search/SearchStack.java
src/main/java/com/kelseyde/calvin/search/Searcher.java

Refactor NMP

---

src/main/java/com/kelseyde/calvin/uci/UCI.java
src/main/java/com/kelseyde/calvin/uci/UCICommandType.java

Implement full UCI support

---

src/main/java/com/kelseyde/calvin/search/SearchHistory.java
src/main/java/com/kelseyde/calvin/search/SearchResult.java
src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/java/com/kelseyde/calvin/search/ThreadData.java

```
Elo   | 1.88 +- 3.80 (95%)
LLR   | 2.20 (-2.20, 2.20) [-5.00, 0.00]
Games | N: 8696 W: 2111 L: 2064 D: 4521
Penta | [54, 945, 2298, 1002, 49]
```
https://kelseyde.pythonanywhere.com/test/681/
bench 4189467

Refactor aspiration windows code

---

src/main/java/com/kelseyde/calvin/uci/UCI.java
src/main/java/com/kelseyde/calvin/utils/Bench.java

Call System.gc() inbetween positions during bench

---

src/main/java/com/kelseyde/calvin/engine/Engine.java
src/main/java/com/kelseyde/calvin/search/ParallelSearcher.java
src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/java/com/kelseyde/calvin/tables/tt/HashEntry.java
src/main/java/com/kelseyde/calvin/tables/tt/TranspositionTable.java
src/test/java/com/kelseyde/calvin/tables/TranspositionTableTest.java

Revert stupid tt memory shit

---

src/main/java/com/kelseyde/calvin/search/ParallelSearcher.java
src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/java/com/kelseyde/calvin/search/ThreadData.java
src/main/java/com/kelseyde/calvin/search/picker/MovePicker.java
src/main/java/com/kelseyde/calvin/search/picker/MoveScorer.java
src/main/java/com/kelseyde/calvin/search/picker/QuiescentMovePicker.java
src/main/java/com/kelseyde/calvin/search/picker/ScoredMove.java
src/main/java/com/kelseyde/calvin/search/picker/StandardMovePicker.java
src/test/java/com/kelseyde/calvin/search/MovePickerTest.java

Stopping early
```
Elo   | 3.13 +- 6.23 (95%)
SPRT  | 8.0+0.08s Threads=2 Hash=8MB
LLR   | 1.16 (-2.20, 2.20) [-5.00, 0.00]
Games | N: 3330 W: 817 L: 787 D: 1726
Penta | [10, 399, 827, 409, 20]
```
https://kelseyde.pythonanywhere.com/test/719/
bench 3456011

Only main thread checks limits

---

src/main/java/com/kelseyde/calvin/engine/EngineConfig.java
src/main/java/com/kelseyde/calvin/search/SearchStack.java
src/main/java/com/kelseyde/calvin/search/Searcher.java

```
Elo   | 5.23 +- 3.95 (95%)
LLR   | 2.20 (-2.20, 2.20) [0.00, 4.00]
Games | N: 8642 W: 2191 L: 2061 D: 4390
Penta | [51, 971, 2164, 1067, 68]
```
https://kelseyde.pythonanywhere.com/test/761/
bench 3444991

Increase RFP if parent node was PV

---

src/main/java/com/kelseyde/calvin/board/Bits.java
src/main/java/com/kelseyde/calvin/board/Board.java
src/main/java/com/kelseyde/calvin/board/Key.java
src/main/java/com/kelseyde/calvin/engine/Tunable.java
src/main/java/com/kelseyde/calvin/evaluation/Accumulator.java
src/main/java/com/kelseyde/calvin/evaluation/Feature.java
src/main/java/com/kelseyde/calvin/evaluation/NNUE.java
src/main/java/com/kelseyde/calvin/evaluation/activation/Crelu.java
src/main/java/com/kelseyde/calvin/evaluation/activation/Screlu.java
src/main/java/com/kelseyde/calvin/movegen/MoveGenerator.java
src/main/java/com/kelseyde/calvin/search/SEE.java
src/main/java/com/kelseyde/calvin/search/Score.java
src/main/java/com/kelseyde/calvin/search/SearchHistory.java
src/main/java/com/kelseyde/calvin/search/SearchLimits.java
src/main/java/com/kelseyde/calvin/search/Searcher.java
src/main/java/com/kelseyde/calvin/search/ordering/QuiescentMovePicker.java
src/main/java/com/kelseyde/calvin/search/ordering/StandardMovePicker.java
src/main/java/com/kelseyde/calvin/tables/tt/HashEntry.java
src/main/java/com/kelseyde/calvin/tables/tt/TranspositionTable.java
src/main/java/com/kelseyde/calvin/uci/Pretty.java
src/main/java/com/kelseyde/calvin/uci/UCICommandType.java
src/test/java/com/kelseyde/calvin/movegen/drawcalculator/DrawByFiftyMoveRuleTest.java
src/test/java/com/kelseyde/calvin/movegen/drawcalculator/DrawByInsufficientMaterialTest.java
src/test/java/com/kelseyde/calvin/movegen/drawcalculator/DrawByRepetitionTest.java
src/test/java/com/kelseyde/calvin/movegen/drawcalculator/DrawByStalemateTest.java

Just a big refactor really. Added comments and formatting in a lot of places. Ran a quick (4+0.4) non-reg to see if removing final makes any difference. Stopping early because this acceptable to me.
```
Elo   | -1.83 +- 2.54 (95%)
SPRT  | 4.0+0.04s Threads=1 Hash=8MB
LLR   | -0.73 (-2.20, 2.20) [-5.00, 0.00]
Games | N: 22348 W: 5637 L: 5755 D: 10956
Penta | [246, 2588, 5579, 2560, 201]
```
https://chess.n9x.co/test/2281/
bench 1206809

Remove final keyword
